/*
 * Foundation aptitude is deliberately a small, curated placement bank rather
 * than a random arithmetic generator.  Each topic has a consistent 5/10/5
 * Conceptual / Standard / Advanced mix.  The checks at the bottom make a bad
 * option set or an accidental answer-key mismatch fail during development.
 */
const levelFor = index => index < 5 ? 'Conceptual Placement' : index < 15 ? 'Standard Placement' : 'Advanced Placement';
const difficultyFor = index => index < 5 ? 'Easy' : index < 15 ? 'Medium' : 'Hard';
const timeFor = index => index < 5 ? 45 : index < 15 ? 60 : 90;
const text = value => String(value);
const gcd = (a, b) => b ? gcd(b, a % b) : Math.abs(a);
const fraction = (numerator, denominator) => {
  const factor = gcd(numerator, denominator);
  return `${numerator / factor}/${denominator / factor}`;
};
const format = value => Number.isInteger(value) ? String(value) : String(Number(value.toFixed(2)));

const optionSet = (answer, wrong, seed) => {
  const correct = text(answer);
  const choices = [correct, ...wrong.map(text)].filter((item, index, all) => all.indexOf(item) === index);
  if (choices.length !== 4) throw new Error(`Question option set needs four unique values; got ${choices.join(', ')}`);
  const offset = seed % 4;
  const options = [...choices.slice(offset), ...choices.slice(0, offset)];
  return { options, correctAnswer: options.indexOf(correct) };
};
const question = (topic, index, { prompt, answer, wrong, explanation, shortcut = null, formulaIds = [], tags = [], setId = null, setContext = null }) => ({
  id: `foundation-${topic}-${String(index + 1).padStart(3, '0')}`,
  track: 'foundation',
  topic,
  placementLevel: levelFor(index),
  difficulty: difficultyFor(index),
  estimatedTimeSeconds: timeFor(index),
  question: prompt,
  ...optionSet(answer, wrong, index),
  explanation,
  shortcut,
  formulaIds,
  tags,
  setId,
  setContext
});
const q = (topic, index, fields) => question(topic, index, fields);

export const aptitudeTopics = [
  ['percentages', 'Percentages', 'Arithmetic & Commercial Math'],
  ['ratio-proportion', 'Ratio & Proportion', 'Arithmetic & Commercial Math'],
  ['profit-loss', 'Profit & Loss', 'Arithmetic & Commercial Math'],
  ['discount', 'Discount', 'Arithmetic & Commercial Math'],
  ['average', 'Average', 'Arithmetic & Commercial Math'],
  ['ages', 'Ages', 'Arithmetic & Commercial Math'],
  ['mixture-alligation', 'Mixture & Alligation', 'Arithmetic & Commercial Math'],
  ['partnership', 'Partnership', 'Arithmetic & Commercial Math'],
  ['simple-interest', 'Simple Interest', 'Arithmetic & Commercial Math'],
  ['compound-interest', 'Compound Interest', 'Arithmetic & Commercial Math'],
  ['time-work', 'Time & Work', 'Work, Time & Motion'],
  ['work-wages', 'Work & Wages', 'Work, Time & Motion'],
  ['pipes-cisterns', 'Pipes & Cisterns', 'Work, Time & Motion'],
  ['speed-distance-time', 'Time, Speed & Distance', 'Work, Time & Motion'],
  ['trains', 'Trains', 'Work, Time & Motion'],
  ['boats-streams', 'Boats & Streams', 'Work, Time & Motion'],
  ['races', 'Races', 'Work, Time & Motion'],
  ['number-system', 'Number System', 'Numbers & Algebra'],
  ['lcm-hcf', 'LCM & HCF', 'Numbers & Algebra'],
  ['simplification', 'Simplification', 'Numbers & Algebra'],
  ['algebra', 'Algebra', 'Numbers & Algebra'],
  ['progressions', 'Progressions', 'Numbers & Algebra'],
  ['logarithms', 'Logarithms', 'Numbers & Algebra'],
  ['permutation-combination', 'Permutation & Combination', 'Numbers & Algebra'],
  ['probability', 'Probability', 'Numbers & Algebra'],
  ['geometry', 'Geometry', 'Geometry & Measurement'],
  ['mensuration', 'Mensuration', 'Geometry & Measurement'],
  ['clocks', 'Clocks', 'Geometry & Measurement'],
  ['calendars', 'Calendars', 'Geometry & Measurement'],
  ['data-interpretation', 'Data Interpretation', 'Reasoning & Language'],
  ['logical-reasoning', 'Logical Reasoning', 'Reasoning & Language'],
  ['verbal-ability', 'Verbal Ability', 'Reasoning & Language']
].map(([id, name, category]) => ({ id, name, category }));

export const aptitudeCategories = [...new Set(aptitudeTopics.map(topic => topic.category))].map(category => ({
  category,
  topics: aptitudeTopics.filter(topic => topic.category === category)
}));

const formula = (id, topic, title, expression, description, variables, whenToUse, example, calculatorType = 'percentage-change') => ({
  id, topic, title, formula: expression, description, variables, whenToUse, example, calculatorType,
  quickCheck: null
});
export const formulaCatalog = [
  formula('percentage-change', 'percentages', 'Percentage change', 'Change % = (New − Old) / Old × 100', 'Measures change from the original value.', ['Old value', 'New value'], 'Comparing a revised value with its base.', '80 to 100 is a 25% increase.'),
  formula('ratio-share', 'ratio-proportion', 'Ratio share', 'Share = Ratio part / Total parts × Total', 'Converts a ratio into an actual share.', ['Ratio parts', 'Total quantity'], 'Dividing money, quantities or work in a ratio.', 'In 2:3 of 250, the shares are 100 and 150.', 'ratio-share'),
  formula('profit-percent', 'profit-loss', 'Profit or loss percentage', 'Profit % = (SP − CP) / CP × 100', 'Always use cost price as the base for profit percentage.', ['Cost price', 'Selling price'], 'Comparing selling and cost prices.', 'CP 100, SP 120 gives 20% profit.', 'profit-loss'),
  formula('discount', 'discount', 'Discount', 'Discount % = (MP − SP) / MP × 100', 'Discount is measured against marked price.', ['Marked price', 'Selling price'], 'Marked-price and sale-price questions.', '20% off 500 gives a selling price of 400.', 'profit-loss'),
  formula('average', 'average', 'Average', 'Average = Sum of observations / Number of observations', 'Use totals when groups have unequal sizes.', ['Values'], 'Combined groups, replacement and weighted averages.', 'Total 300 for 5 values has average 60.', 'average'),
  formula('simple-interest', 'simple-interest', 'Simple interest', 'SI = P × R × T / 100', 'Interest is calculated only on principal.', ['Principal', 'Rate %', 'Time in years'], 'Straight interest and amount difference questions.', '1000 at 10% for 2 years earns 200.', 'simple-interest'),
  formula('compound-interest', 'compound-interest', 'Compound interest', 'A = P(1 + R/100)^T', 'Each period earns interest on the updated amount.', ['Principal', 'Rate %', 'Time in years'], 'Growth, depreciation and compound interest.', '1000 at 10% for 2 years becomes 1210.', 'compound-interest'),
  formula('time-work', 'time-work', 'Work rate', 'Combined rate = 1/A + 1/B', 'Represent one day’s work as a fraction.', ['Days A takes', 'Days B takes'], 'People or machines working together.', 'A in 6 days and B in 3 days finish in 2 days.', 'time-work'),
  formula('speed-distance-time', 'speed-distance-time', 'Speed, distance and time', 'Distance = Speed × Time', 'Keep units consistent before calculating.', ['Distance', 'Speed'], 'Journeys, average speed and relative speed.', '120 km at 60 km/h takes 2 hours.', 'speed-distance-time'),
  formula('boats-streams', 'boats-streams', 'Boat and stream', 'Downstream = b + s; Upstream = b − s', 'Boat speed is in still water; stream speed is the current.', ['Boat speed', 'Stream speed'], 'Upstream/downstream travel.', '10 km/h boat and 2 km/h stream: 12 downstream, 8 upstream.', 'boats-streams'),
  formula('mixture', 'mixture-alligation', 'Alligation', 'Quantity ratio = (Higher − Mean) : (Mean − Lower)', 'Cross-difference yields the mixing ratio.', ['Lower value', 'Higher value', 'Mean value'], 'Two-component concentration or price mixtures.', '20 and 50 to get 30: 2:1.', 'ratio-share'),
  formula('partnership', 'partnership', 'Partnership share', 'Profit share ∝ Capital × Time', 'Capital invested for longer earns a larger share.', ['Capital', 'Months invested'], 'Partners joining at different times.', '10k for 12 months equals 15k for 8 months.', 'ratio-share'),
  formula('pipes', 'pipes-cisterns', 'Pipes and cisterns', 'Net rate = Fill rates − Empty rates', 'Use signed work rates, just as in Time & Work.', ['Fill days', 'Empty days'], 'Tank-filling and leakage questions.', 'Pipe in 6 h and leak in 12 h fill in 12 h.', 'time-work'),
  formula('trains', 'trains', 'Train crossing', 'Time = Total distance / Relative speed', 'Total distance is the sum of train/platform lengths.', ['Distance', 'Speed'], 'Crossing a pole, platform or another train.', '180 m train at 54 km/h crosses a pole in 12 s.', 'speed-distance-time'),
  formula('number-system', 'number-system', 'Number system', 'Dividend = Divisor × Quotient + Remainder', 'Remainder is always smaller than the divisor.', ['Dividend', 'Divisor'], 'Divisibility and remainder reasoning.', '29 = 6×4 + 5.', 'percentage-change'),
  formula('lcm-hcf', 'lcm-hcf', 'LCM and HCF', 'For two numbers: Product = LCM × HCF', 'The relation applies to exactly two positive integers.', ['First number', 'Second number'], 'Recovering LCM/HCF from two number facts.', '12×18 = 6×36.', 'percentage-change'),
  formula('permutation-combination', 'permutation-combination', 'Counting', 'nPr = n!/(n−r)!; nCr = n!/[r!(n−r)!]', 'Order matters for arrangements, not for selections.', ['n objects', 'r selected'], 'Committees, arrangements and selections.', '5C2 = 10 and 5P2 = 20.', 'percentage-change'),
  formula('probability', 'probability', 'Probability', 'P(Event) = Favourable outcomes / Total outcomes', 'For dependent events, multiply conditional probabilities.', ['Favourable outcomes', 'Total outcomes'], 'Cards, balls, dice and selections.', 'P(even on a die) = 3/6 = 1/2.', 'percentage-change'),
  formula('mensuration', 'mensuration', 'Mensuration', 'Cylinder TSA = 2πr(r + h)', 'Choose the relevant area or volume formula.', ['Radius', 'Height'], 'Areas, volumes and surface areas.', 'For r=7, h=10, TSA is 748 cm².', 'percentage-change'),
  formula('progressions', 'progressions', 'Arithmetic progression', 'aₙ = a + (n−1)d; Sₙ = n/2[2a+(n−1)d]', 'A constant difference identifies an AP.', ['First term', 'Difference'], 'Term and sum questions.', '3, 7, 11 has d=4.', 'percentage-change'),
  formula('logarithms', 'logarithms', 'Logarithms', 'logₐ(xy) = logₐx + logₐy', 'Translate powers into logarithms and vice versa.', ['Base', 'Argument'], 'Exponents and logarithmic equations.', 'log₂8 = 3.', 'percentage-change'),
  formula('geometry', 'geometry', 'Geometry essentials', 'Triangle angle sum = 180°', 'Use a diagram and mark the known relationships first.', ['Angles', 'Sides'], 'Triangle and circle angle relationships.', 'Angles 50° and 60° leave 70°.', 'percentage-change'),
  formula('clocks', 'clocks', 'Clock angle', '|30H − 5.5M| degrees', 'Use hour and minute hand positions at the exact minute.', ['Hour', 'Minute'], 'Angles and coincidence of clock hands.', 'At 3:00 the angle is 90°.', 'percentage-change'),
  formula('calendars', 'calendars', 'Calendar odd days', 'Normal year = 1 odd day; leap year = 2', 'Reduce day differences modulo 7.', ['Years', 'Days'], 'Day-of-week and leap-year cycles.', '365 days shifts the weekday by one.', 'percentage-change')
];

const numericBuilders = {
  percentages: i => {
    const percentagePairs = [[60, 75], [64, 80], [72, 90], [70, 84], [55, 66]]; const [a, b] = percentagePairs[i % 5]; const divisor = gcd(a, b);
    if (i % 5 === 0) { const answer = `${b / divisor}:${a / divisor}`; return q('percentages', i, { prompt: `${a}% of A equals ${b}% of B. What is A:B?`, answer, wrong: [`${a / divisor}:${b / divisor}`, `${a}:${b}`, `${b / 5}:${a / 5}`], explanation: `${a}A/100 = ${b}B/100, so A:B = ${b}:${a}; reducing gives ${answer}.`, shortcut: 'Cross the percentages: A:B is the reverse of the percentage ratio.', formulaIds: ['percentage-change'], tags: ['Percentage relationship', 'Ratio'] }); }
    if (i % 5 === 1) { const base = 20000 + (i % 4) * 2000; const rise = 20; const cut = 10; const answer = base * 1.2 * .9; return q('percentages', i, { prompt: `A salary of ₹${base} rises by ${rise}% and then falls by ${cut}%. What is the final salary?`, answer: `₹${answer}`, wrong: [`₹${base * 1.1}`, `₹${base}`, `₹${base * 1.3}`], explanation: `Apply successive multipliers: ${base} × 1.20 × 0.90 = ₹${answer}.`, shortcut: 'A +20%, −10% sequence is a net +8%, not +10%.', formulaIds: ['percentage-change'], tags: ['Successive percentage', 'Salary'] }); }
    if (i % 5 === 2) { const pass = 36 + (i % 4) * 2; const fail = 24; const total = 250; const answer = total * pass / 100; return q('percentages', i, { prompt: `In a test, ${pass}% of ${total} students pass. How many fail?`, answer: total - answer, wrong: [answer, total - answer + 10, total - answer - 10], explanation: `Passed = ${pass}% of ${total} = ${answer}; failed = ${total} − ${answer} = ${total - answer}.`, shortcut: 'Find the complement percentage first: ${100 - pass}% fail.', formulaIds: ['percentage-change'], tags: ['Percentage', 'Complement'] }); }
    if (i % 5 === 3) { const expense = 70 + (i % 3) * 5; const income = 4000; const answer = (100 - expense) / expense * 100; return q('percentages', i, { prompt: `A person spends ${expense}% of income. Savings are what percent of expenditure?`, answer: `${format(answer)}%`, wrong: [`${100 - expense}%`, `${expense}%`, `${format(answer + 10)}%`], explanation: `Assume income 100. Savings = ${100 - expense}; expenditure = ${expense}. Thus savings/expenditure × 100 = ${format(answer)}%.`, shortcut: 'For “percent of expenditure”, use expenditure—not income—as the base.', formulaIds: ['percentage-change'], tags: ['Percentage base', 'Savings'] }); }
    const marked = 1000 + (i % 4) * 200; const discount = 20; const gst = 10; const answer = marked * .8 * 1.1; return q('percentages', i, { prompt: `A product marked ₹${marked} gets a ${discount}% discount, then ${gst}% GST on the discounted price. What is paid?`, answer: `₹${answer}`, wrong: [`₹${marked * .9}`, `₹${marked * .8}`, `₹${marked * 1.1}`], explanation: `Discounted price = ${marked} × .8. GST applies to that: ${marked} × .8 × 1.1 = ₹${answer}.`, shortcut: 'Discount and tax are successive multipliers.', formulaIds: ['percentage-change', 'discount'], tags: ['Percentage', 'Discount', 'GST'] });
  },
  'ratio-proportion': i => {
    const x = 3 + (i % 4); const y = 4 + (i % 3); const z = 5 + (i % 3);
    if (i % 5 === 0) { const answer = `${x}:${z}`; return q('ratio-proportion', i, { prompt: `If A:B = ${x}:${y} and B:C = ${y}:${z}, what is A:C?`, answer, wrong: [`${x}:${y}`, `${z}:${x}`, `${x * y}:${z}`], explanation: `The shared B part is already ${y}. So A:B:C = ${x}:${y}:${z}, hence A:C = ${x}:${z}.`, shortcut: 'Align the common term before combining ratios.', formulaIds: ['ratio-share'], tags: ['Ratio', 'Proportion'] }); }
    if (i % 5 === 1) { const total = (x + y) * 90; const answer = total * y / (x + y); return q('ratio-proportion', i, { prompt: `₹${total} is divided between A and B in the ratio ${x}:${y}. What does B receive?`, answer: `₹${answer}`, wrong: [`₹${total * x / (x + y)}`, `₹${total / 2}`, `₹${answer + 135}`], explanation: `There are ${x + y} parts. B has ${y}, so B = ${y}/${x + y} × ${total} = ₹${answer}.`, shortcut: 'Find one ratio part: ₹${total / (x + y)}.', formulaIds: ['ratio-share'], tags: ['Ratio share', 'Distribution'] }); }
    if (i % 5 === 2) { const boys = 4 + i % 3; const girls = 5 + i % 4; const add = girls; const answer = `${boys}:${girls + add}`; return q('ratio-proportion', i, { prompt: `The ratio of boys to girls is ${boys}:${girls}. If ${add} girls join, what is the new ratio?`, answer, wrong: [`${boys + add}:${girls}`, `${boys}:${girls}`, `${boys + add}:${girls + add}`], explanation: `Only the girls count changes: ${boys}:(${girls}+${add}) = ${answer}.`, shortcut: 'Update only the group described in the change.', formulaIds: ['ratio-share'], tags: ['Ratio', 'Change'] }); }
    if (i % 5 === 3) { const first = 2 + i % 3; const second = 3 + i % 4; const total = (first + second) * 12; return q('ratio-proportion', i, { prompt: `Two numbers are in ratio ${first}:${second} and differ by ${total - total * first / (first + second)}. What is the larger number?`, answer: total * second / (first + second), wrong: [total * first / (first + second), total, total / second], explanation: `Let numbers be ${first}k and ${second}k. Their difference fixes k, giving the larger number ${total * second / (first + second)}.`, shortcut: 'Use the difference in ratio parts to find one part.', formulaIds: ['ratio-share'], tags: ['Ratio', 'Difference'] }); }
    const original = 80 + i % 4 * 20; const increase = 25; const answer = original * 1.25; return q('ratio-proportion', i, { prompt: `A recipe uses flour and sugar in ratio 5:2. If flour becomes ${increase}% more while sugar stays the same, what is the new ratio?`, answer: `${5 * 1.25}:2`, wrong: ['5:2', `${5}:${2 * 1.25}`, '6:3'], explanation: `Only flour changes: 5 × 1.25 : 2 = 6.25:2, equivalent to 25:8.`, shortcut: 'Apply the percentage multiplier to the affected ratio part only.', formulaIds: ['ratio-share', 'percentage-change'], tags: ['Ratio', 'Percentage'] });
  },
  'profit-loss': i => {
    const cp = 500 + (i % 4) * 100;
    if (i % 5 === 0) { const profit = 20 + i % 3 * 5; const sp = cp * (1 + profit / 100); return q('profit-loss', i, { prompt: `An article is sold for ₹${sp} at a ${profit}% profit. Find its cost price.`, answer: `₹${cp}`, wrong: [`₹${sp * (1 - profit / 100)}`, `₹${sp - profit}`, `₹${sp}`], explanation: `SP = CP × ${100 + profit}/100. Therefore CP = ${sp} × 100/${100 + profit} = ₹${cp}.`, shortcut: 'For reverse profit, divide by the selling multiplier.', formulaIds: ['profit-percent'], tags: ['Profit', 'Reverse percentage'] }); }
    if (i % 5 === 1) { const gain = 25; const loss = 20; const answer = (1 + gain / 100) * (1 - loss / 100) - 1; return q('profit-loss', i, { prompt: `A trader gains ${gain}% on one item and loses ${loss}% on another with equal cost prices. What is the overall result?`, answer: `${format(answer * 100)}% profit`, wrong: ['5% profit', '5% loss', `${format(Math.abs(answer) * 100)}% loss`], explanation: `For equal CP, average the selling multipliers: 1.25 and .80; together they give 1.025, or 2.5% profit.`, shortcut: 'Equal costs: compare total SP to total CP, not the percentages directly.', formulaIds: ['profit-percent'], tags: ['Profit & loss', 'Equal cost price'] }); }
    if (i % 5 === 2) { const markedGain = 50; const disc = 20; const answer = (1 + markedGain / 100) * (1 - disc / 100) - 1; return q('profit-loss', i, { prompt: `An item is marked ${markedGain}% above cost and sold after a ${disc}% discount. What is the profit percentage?`, answer: `${format(answer * 100)}%`, wrong: [`${markedGain - disc}%`, `${disc}%`, `${markedGain}%`], explanation: `SP/CP = 1.50 × .80 = 1.20, so the profit is 20%.`, shortcut: 'Multiply mark-up and discount factors.', formulaIds: ['profit-percent', 'discount'], tags: ['Profit', 'Discount', 'Marked price'] }); }
    if (i % 5 === 3) { const loss = 12.5; const sp = 700 + (i % 3) * 140; const answer = sp / (1 - loss / 100); return q('profit-loss', i, { prompt: `At a ${loss}% loss, an article sells for ₹${sp}. What was its cost price?`, answer: `₹${answer}`, wrong: [`₹${sp * (1 - loss / 100)}`, `₹${sp + loss}`, `₹${sp}`], explanation: `A 12.5% loss means SP = 87.5% = 7/8 of CP. CP = ${sp} × 8/7 = ₹${answer}.`, shortcut: '12.5% is 1/8, so use the fraction 7/8.', formulaIds: ['profit-percent'], tags: ['Loss', 'Fractions'] }); }
    const x = 20; const y = 25; return q('profit-loss', i, { prompt: `A seller gives a ${x}% discount but still earns ${y}% profit. By what percent above cost was the item marked?`, answer: '56.25%', wrong: ['45%', '5%', '25%'], explanation: `MP × .80 = CP × 1.25, so MP/CP = 1.25/.80 = 1.5625. Mark-up = 56.25%.`, shortcut: 'Set discounted marked price equal to the desired selling-price multiplier.', formulaIds: ['profit-percent', 'discount'], tags: ['Profit', 'Discount', 'Reverse calculation'] });
  },
  discount: i => {
    const mp = 1000 + (i % 4) * 200;
    if (i % 5 === 0) { const d1 = 20; const d2 = 10; const answer = mp * .8 * .9; return q('discount', i, { prompt: `A marked price of ₹${mp} has successive discounts of ${d1}% and ${d2}%. What is the selling price?`, answer: `₹${answer}`, wrong: [`₹${mp * .7}`, `₹${mp * .9}`, `₹${mp * .8}`], explanation: `Successive discounts multiply: ${mp} × .80 × .90 = ₹${answer}.`, shortcut: 'Do not add successive discounts; multiply their remaining factors.', formulaIds: ['discount'], tags: ['Discount', 'Successive change'] }); }
    if (i % 5 === 1) { const discount = 25; const sp = mp * .75; return q('discount', i, { prompt: `After a ${discount}% discount, a product sells for ₹${sp}. What was its marked price?`, answer: `₹${mp}`, wrong: [`₹${sp * 1.25}`, `₹${sp}`, `₹${sp / .25}`], explanation: `SP is 75% of MP. MP = ${sp}/.75 = ₹${mp}.`, shortcut: 'Reverse a discount by dividing by the remaining percentage.', formulaIds: ['discount'], tags: ['Discount', 'Reverse percentage'] }); }
    if (i % 5 === 2) { const first = 30; const answer = 100 - (100 - first) * .8; return q('discount', i, { prompt: `A store offers ${first}% off and then a further 20% off. What is the equivalent single discount?`, answer: `${answer}%`, wrong: ['50%', '44%', '20%'], explanation: `Remaining price = 70% × 80% = 56%, so discount = 44%.`, shortcut: 'Equivalent discount = 100 − product of remaining percentages.', formulaIds: ['discount'], tags: ['Equivalent discount'] }); }
    if (i % 5 === 3) { const cash = 15; const card = 10; return q('discount', i, { prompt: `A customer can take ${cash}% cash discount or ${card}% discount followed by 5% cashback. Which saves more on a ₹${mp} purchase?`, answer: 'Cash discount', wrong: ['Card discount with cashback', 'Both save equally', 'Cannot be determined'], explanation: `Cash saves ₹${mp * .15}. Card saves ₹${mp * .1} + ₹${mp * .9 * .05} = ₹${mp * .145}; cash is higher.`, shortcut: 'Cashback usually applies after the discount, so compute it on the reduced amount.', formulaIds: ['discount'], tags: ['Discount', 'Cashback', 'Comparison'] }); }
    const markup = 40; const target = 12; const answer = 100 - (100 + target) / (100 + markup) * 100; return q('discount', i, { prompt: `An article is marked ${markup}% above cost. What discount gives a ${target}% profit?`, answer: `${format(answer)}%`, wrong: ['28%', '12%', '40%'], explanation: `Required SP/CP = 1.12 and MP/CP = 1.40. Discount = 1 − 1.12/1.40 = 20%.`, shortcut: 'Divide the target SP multiplier by the mark-up multiplier.', formulaIds: ['discount', 'profit-percent'], tags: ['Discount', 'Profit', 'Marked price'] });
  },
  average: i => {
    if (i % 5 === 0) { const n = 10; const average = 52 + i % 3 * 2; const removed = 70; const answer = (n * average - removed) / (n - 1); return q('average', i, { prompt: `The average of ${n} scores is ${average}. If a score of ${removed} is removed, what is the new average?`, answer: format(answer), wrong: [String(average), format(answer + 2), format(answer - 2)], explanation: `Original total = ${n}×${average} = ${n * average}. Remove ${removed}; divide ${n * average - removed} by 9 = ${format(answer)}.`, shortcut: 'Convert the average to a total before removing an observation.', formulaIds: ['average'], tags: ['Average', 'Removal'] }); }
    if (i % 5 === 1) { const n1 = 20; const a1 = 60; const n2 = 30; const a2 = 70; const answer = (n1 * a1 + n2 * a2) / (n1 + n2); return q('average', i, { prompt: `A group of ${n1} has average ${a1}; a group of ${n2} has average ${a2}. What is their combined average?`, answer, wrong: [65, 66, 68], explanation: `Combined total = ${n1 * a1}+${n2 * a2}=${n1 * a1 + n2 * a2}. Divide by ${n1 + n2}: ${answer}.`, shortcut: 'A combined average is weighted toward the larger group.', formulaIds: ['average'], tags: ['Weighted average', 'Groups'] }); }
    if (i % 5 === 2) { const count = 8; const avg = 35; const newValue = 53; const answer = (count * avg + newValue) / (count + 1); return q('average', i, { prompt: `The average of ${count} values is ${avg}. When ${newValue} is added, what is the new average?`, answer: format(answer), wrong: [format(avg + newValue / count), String(avg), format(answer + 1)], explanation: `Total becomes ${count * avg}+${newValue}=${count * avg + newValue}; divide by 9 to get ${format(answer)}.`, shortcut: 'Use total sum, not an average-of-averages shortcut.', formulaIds: ['average'], tags: ['Average', 'Addition'] }); }
    if (i % 5 === 3) { const old = 48; const newValue = 66; const count = 12; const answer = old + (newValue - 42) / count; return q('average', i, { prompt: `In a set of ${count} numbers with average ${old}, one value ${42} is replaced by ${newValue}. What is the new average?`, answer, wrong: [old + newValue - 42, old, answer + 1], explanation: `The total rises by ${newValue - 42}. Dividing this change by ${count} raises the average by ${(newValue - 42) / count}, to ${answer}.`, shortcut: 'Replacement changes an average by (new − old item)/count.', formulaIds: ['average'], tags: ['Average', 'Replacement'] }); }
    const men = 6; const women = 4; const menAvg = 70; const totalAvg = 64; const answer = (totalAvg * (men + women) - men * menAvg) / women; return q('average', i, { prompt: `The average score of ${men + women} students is ${totalAvg}. If ${men} boys average ${menAvg}, what is the girls’ average?`, answer, wrong: [totalAvg, menAvg, answer + 5], explanation: `Total score = ${men + women}×${totalAvg}=${(men + women) * totalAvg}. Boys contribute ${men * menAvg}; girls average = ${((men + women) * totalAvg - men * menAvg)}/${women}=${answer}.`, shortcut: 'Work backward from the combined total.', formulaIds: ['average'], tags: ['Average', 'Weighted average', 'Reverse calculation'] });
  },
  ages: i => {
    if (i % 5 === 0) { const son = 12 + i % 3; const father = son * 3; const after = 6; return q('ages', i, { prompt: `A father is three times his son’s age. In ${after} years, what will their age ratio be if the son is now ${son}?`, answer: `${father + after}:${son + after}`, wrong: [`3:1`, `${father}:${son}`, `${father - after}:${son + after}`], explanation: `Current ages are ${father} and ${son}; add ${after} to each, giving ${father + after}:${son + after}.`, shortcut: 'A time shift applies to both people, not to the ratio.', formulaIds: ['average'], tags: ['Ages', 'Ratio'] }); }
    if (i % 5 === 1) { const now = 24; const difference = 12; return q('ages', i, { prompt: `The sum of A and B’s ages is ${now + difference}. A is ${difference} years older than B. What is B’s age?`, answer: now / 2, wrong: [difference, now, (now + difference) / 2], explanation: `Let B=x, A=x+${difference}. Then 2x+${difference}=${now + difference}; x=${now / 2}.`, shortcut: 'Subtract the age difference from the sum, then halve.', formulaIds: ['average'], tags: ['Ages', 'Linear equation'] }); }
    if (i % 5 === 2) { const present = 30; const ago = 5; const ratio = '5:3'; const answer = present + ago; return q('ages', i, { prompt: `${ago} years ago, A:B was ${ratio}. If B is now ${present}, what is A’s current age?`, answer, wrong: [present, present * 5 / 3, answer + ago], explanation: `B was ${present - ago}, so one ratio part is ${(present - ago) / 3}; A was ${(present - ago) / 3 * 5}, hence now ${answer}.`, shortcut: 'First move both ages to the time where the ratio is given.', formulaIds: ['ratio-share'], tags: ['Ages', 'Ratio'] }); }
    if (i % 5 === 3) { const mother = 42; const daughter = 14; const years = 14; return q('ages', i, { prompt: `A mother is ${mother} and her daughter is ${daughter}. After how many years will the mother be twice the daughter’s age?`, answer: years, wrong: [7, 21, 0], explanation: `42+x = 2(14+x). Solving gives x=14.`, shortcut: 'Use an equation; ratios change with time.', formulaIds: ['ratio-share'], tags: ['Ages', 'Equation'] }); }
    const a = 18; const b = 30; const multiplier = 2; const answer = (b - multiplier * a) / (multiplier - 1); return q('ages', i, { prompt: `After how many years will a ${b}-year-old be twice as old as an ${a}-year-old?`, answer, wrong: [b - a, a, b / 2], explanation: `${b}+x = 2(${a}+x), so x = ${answer}.`, shortcut: 'Set “older after x” equal to the required multiple of “younger after x”.', formulaIds: ['ratio-share'], tags: ['Ages', 'Algebra'] });
  },
  'mixture-alligation': i => {
    const low = 20 + i % 3 * 5; const high = 50 + i % 3 * 10; const mean = 35 + i % 2 * 5;
    if (i % 5 === 0) { const left = high - mean; const right = mean - low; return q('mixture-alligation', i, { prompt: `In what ratio should ${low}% and ${high}% solutions be mixed to obtain ${mean}%?`, answer: `${left}:${right}`, wrong: [`${right}:${left}`, '1:1', `${mean - low}:${high - mean}`], explanation: `Alligation gives lower:higher = (${high}−${mean}):(${mean}−${low}) = ${left}:${right}.`, shortcut: 'Cross-subtract; the differences go to the opposite quantities.', formulaIds: ['mixture'], tags: ['Mixture', 'Alligation'] }); }
    if (i % 5 === 1) { const cheap = 30; const dear = 50; const target = 38; const answer = `${dear - target}:${target - cheap}`; return q('mixture-alligation', i, { prompt: `Tea costing ₹${cheap}/kg and ₹${dear}/kg is mixed to make a ₹${target}/kg blend. What is the cheap:dear ratio?`, answer, wrong: [`${target - cheap}:${dear - target}`, '1:1', `${cheap}:${dear}`], explanation: `Cheap:dear = (50−38):(38−30) = 12:8 = 3:2.`, shortcut: 'The mean lies closer to the ingredient used in the larger quantity.', formulaIds: ['mixture'], tags: ['Alligation', 'Price'] }); }
    if (i % 5 === 2) { const total = 20; const milk = 80; const remove = 5; const answer = 60; return q('mixture-alligation', i, { prompt: `A ${total} L mixture has ${milk}% milk. ${remove} L is removed and replaced with water. What percent milk remains?`, answer: `${answer}%`, wrong: ['80%', '64%', '40%'], explanation: `Initial milk = 16 L. Removing 5 L removes 4 L milk, leaving 12 L in 20 L = 60%.`, shortcut: 'Track the pure component, not the percentage alone.', formulaIds: ['mixture'], tags: ['Mixture', 'Replacement'] }); }
    if (i % 5 === 3) { const total = 40; const salt = 25; const remove = 10; const answer = 18.75; return q('mixture-alligation', i, { prompt: `A ${total} L solution contains ${salt}% salt. If ${remove} L is removed and replaced with water, what percent salt remains?`, answer: `${answer}%`, wrong: ['25%', '20%', '15%'], explanation: `Salt initially = 10 L. Removing one-fourth removes 2.5 L, leaving 7.5 L in 40 L = 18.75%.`, shortcut: 'Removing a fraction of a uniform mixture removes the same fraction of salt.', formulaIds: ['mixture'], tags: ['Mixture', 'Replacement'] }); }
    const first = 30; const second = 50; const total = 20; const target = 42; const amountSecond = total * (target - first) / (second - first); return q('mixture-alligation', i, { prompt: `How many litres of a ${second}% solution must be added to ${total - amountSecond} L of a ${first}% solution to get ${total} L of a ${target}% solution?`, answer: `${amountSecond} L`, wrong: [`${total - amountSecond} L`, '10 L', '20 L'], explanation: `Let x be the ${second}% amount: 30(${total}−x)+50x=42×${total}; x=${amountSecond} L.`, shortcut: 'Use alligation ratio, then scale to the total volume.', formulaIds: ['mixture'], tags: ['Alligation', 'Linear equation'] });
  },
  partnership: i => {
    const a = 10000 + i % 3 * 2000; const b = 15000 + i % 3 * 2000;
    if (i % 5 === 0) { const profit = 9000; const shareA = profit * a * 12 / (a * 12 + b * 8); return q('partnership', i, { prompt: `A invests ₹${a} for 12 months; B invests ₹${b} for 8 months. From ₹${profit} profit, what is A’s share?`, answer: `₹${format(shareA)}`, wrong: [`₹${profit / 2}`, `₹${profit * a / (a + b)}`, `₹${profit - shareA}`], explanation: `Shares follow capital×time: ${a}×12 : ${b}×8. A receives ₹${format(shareA)}.`, shortcut: 'Replace each capital with capital-months.', formulaIds: ['partnership'], tags: ['Partnership', 'Capital-time'] }); }
    if (i % 5 === 1) { const months = 6; const profit = 6000; const answer = profit * a * 12 / (a * 12 + b * months); return q('partnership', i, { prompt: `A invests ₹${a} for the whole year. B invests ₹${b} after ${12 - months} months. If profit is ₹${profit}, A’s share is:`, answer: `₹${format(answer)}`, wrong: [`₹${profit / 2}`, `₹${format(profit - answer)}`, `₹${profit * a / (a + b)}`], explanation: `A:B = ${a}×12 : ${b}×${months}. Divide ₹${profit} in this ratio.`, shortcut: 'A late partner contributes only for the months actually invested.', formulaIds: ['partnership'], tags: ['Partnership', 'Joining late'] }); }
    if (i % 5 === 2) { const ratio = '3:2'; const total = 10000; return q('partnership', i, { prompt: `Two partners share profit in ratio ${ratio}. If total profit is ₹${total}, how much more does the first receive?`, answer: '₹2000', wrong: ['₹4000', '₹6000', '₹5000'], explanation: `Difference is one of five parts: ₹${total}/5 = ₹2000.`, shortcut: 'For a difference, use the difference in ratio parts.', formulaIds: ['partnership'], tags: ['Partnership', 'Ratio'] }); }
    if (i % 5 === 3) { const ratioA = 3; const ratioB = 2; const capitalA = 12000; const monthsA = 12; const monthsB = 9; const answer = capitalA * monthsA * ratioB / (ratioA * monthsB); return q('partnership', i, { prompt: `A invests ₹${capitalA} for ${monthsA} months. B joins for ${monthsB} months. If their profit ratio is ${ratioA}:${ratioB}, B’s capital is:`, answer: `₹${answer}`, wrong: ['₹8000', '₹12000', '₹16000'], explanation: `${capitalA}×${monthsA} : B×${monthsB} = ${ratioA}:${ratioB}; B = ₹${answer}.`, shortcut: 'Equate capital-month ratios to the given profit ratio.', formulaIds: ['partnership'], tags: ['Partnership', 'Reverse calculation'] }); }
    return q('partnership', i, { prompt: `A and B invest in a business. A’s capital is twice B’s, but B invests for twice as long. How should profit be divided?`, answer: 'Equally', wrong: ['2:1', '1:2', 'Cannot be determined'], explanation: `A’s capital-time is 2×1; B’s is 1×2. Both are equal, so profit is equal.`, shortcut: 'Compare capital×time, not capital alone.', formulaIds: ['partnership'], tags: ['Partnership', 'Conceptual'] });
  },
  'simple-interest': i => {
    const principal = 4000 + i % 4 * 1000; const rate = 8 + i % 3 * 2;
    if (i % 5 === 0) { const time = 3; const si = principal * rate * time / 100; return q('simple-interest', i, { prompt: `What is the simple interest on ₹${principal} at ${rate}% per annum for ${time} years?`, answer: `₹${si}`, wrong: [`₹${principal * rate / 100}`, `₹${principal + si}`, `₹${si + principal * rate / 100}`], explanation: `SI = PRT/100 = ${principal}×${rate}×${time}/100 = ₹${si}.`, shortcut: 'At simple interest, each year earns the same amount.', formulaIds: ['simple-interest'], tags: ['Simple interest'] }); }
    if (i % 5 === 1) { const years = 4; const interest = principal * rate * years / 100; return q('simple-interest', i, { prompt: `₹${principal} earns ₹${interest} simple interest in ${years} years. What is the annual rate?`, answer: `${rate}%`, wrong: [`${rate * years}%`, `${rate / years}%`, `${interest / principal}%`], explanation: `R = SI×100/(P×T) = ${interest}×100/(${principal}×${years}) = ${rate}%.`, shortcut: 'Rearrange PRT/100 instead of guessing.', formulaIds: ['simple-interest'], tags: ['Simple interest', 'Rate'] }); }
    if (i % 5 === 2) { const diffYears = 3; const diff = principal * rate * diffYears / 100; return q('simple-interest', i, { prompt: `At ${rate}% simple interest, the amount after 5 years exceeds the amount after 2 years by:`, answer: `₹${diff}`, wrong: [`₹${principal * rate * 5 / 100}`, `₹${principal * rate * 2 / 100}`, `₹${diff + principal}`], explanation: `Only the extra ${diffYears} years matter: ${principal}×${rate}×${diffYears}/100 = ₹${diff}.`, shortcut: 'Amount differences under SI depend only on the difference in time.', formulaIds: ['simple-interest'], tags: ['Simple interest', 'Amount difference'] }); }
    if (i % 5 === 3) { const amount = principal * (1 + rate * 2 / 100); return q('simple-interest', i, { prompt: `A sum amounts to ₹${amount} in 2 years and ₹${amount + principal * rate / 100} in 3 years at simple interest. Find the principal.`, answer: `₹${principal}`, wrong: [`₹${amount}`, `₹${principal * rate / 100}`, `₹${principal * 2}`], explanation: `The one-year difference is yearly interest. Here it is ₹${principal * rate / 100}; using amount = P + 2I gives P = ₹${principal}.`, shortcut: 'Consecutive-year amount difference is one year’s SI.', formulaIds: ['simple-interest'], tags: ['Simple interest', 'Consecutive amounts'] }); }
    const doubledYears = 100 / rate; return q('simple-interest', i, { prompt: `At ${rate}% simple interest, in how many years will a sum double?`, answer: `${format(doubledYears)} years`, wrong: [`${format(200 / rate)} years`, `${rate} years`, `${format(doubledYears - 1)} years`], explanation: `To double, SI must equal P: PRT/100=P, so T=100/R=${format(doubledYears)} years.`, shortcut: 'Under SI, doubling time = 100/rate.', formulaIds: ['simple-interest'], tags: ['Simple interest', 'Doubling time'] });
  },
  'compound-interest': i => {
    const p = 10000 + i % 3 * 2000; const r = 10;
    if (i % 5 === 0) { const years = 2; const amount = p * (1 + r / 100) ** years; return q('compound-interest', i, { prompt: `Find the compound interest on ₹${p} at ${r}% per annum for ${years} years, compounded annually.`, answer: `₹${amount - p}`, wrong: [`₹${p * r * years / 100}`, `₹${amount}`, `₹${p * r / 100}`], explanation: `Amount = ${p}×1.1² = ₹${amount}; CI = ₹${amount - p}.`, shortcut: 'For 2 years, CI includes interest-on-interest.', formulaIds: ['compound-interest'], tags: ['Compound interest'] }); }
    if (i % 5 === 1) { const years = 2; const ci = p * ((1 + r / 100) ** years - 1); const si = p * r * years / 100; return q('compound-interest', i, { prompt: `For ₹${p} at ${r}% for ${years} years, by how much does compound interest exceed simple interest?`, answer: `₹${ci - si}`, wrong: [`₹${ci}`, `₹${si}`, `₹${p * r / 100}`], explanation: `CI = ₹${ci}; SI = ₹${si}; difference = ₹${ci - si}.`, shortcut: 'For 2 years, CI−SI = P(r/100)².', formulaIds: ['compound-interest', 'simple-interest'], tags: ['CI vs SI'] }); }
    if (i % 5 === 2) { const decline = 20; const years = 2; const final = p * .8 ** years; return q('compound-interest', i, { prompt: `A machine worth ₹${p} depreciates ${decline}% each year. What is its value after ${years} years?`, answer: `₹${final}`, wrong: [`₹${p * .6}`, `₹${p * .8}`, `₹${p - p * decline * years / 100}`], explanation: `Depreciation compounds: ${p}×.8² = ₹${final}.`, shortcut: 'A repeated decrease uses the same compound multiplier as growth.', formulaIds: ['compound-interest'], tags: ['Depreciation', 'Compound change'] }); }
    if (i % 5 === 3) { const amount = p * 1.21; return q('compound-interest', i, { prompt: `A sum becomes ₹${amount} in 2 years at ${r}% compound interest. What was the principal?`, answer: `₹${p}`, wrong: [`₹${amount / 1.1}`, `₹${amount - p}`, `₹${amount}`], explanation: `P = A/1.1² = ${amount}/1.21 = ₹${p}.`, shortcut: 'To reverse compounding, divide by the full growth factor.', formulaIds: ['compound-interest'], tags: ['Compound interest', 'Reverse calculation'] }); }
    const halfYearRate = 5; const periods = 4; const final = p * (1 + halfYearRate / 100) ** periods; return q('compound-interest', i, { prompt: `₹${p} is compounded half-yearly at ${r}% per annum. What is the amount after 2 years?`, answer: `₹${format(final)}`, wrong: [`₹${p * 1.1 ** 2}`, `₹${p + p * r * 2 / 100}`, `₹${p * 1.05 ** 2}`], explanation: `Half-yearly rate is 5%, with 4 periods: ${p}×1.05⁴ = ₹${format(final)}.`, shortcut: 'Change both the rate and number of periods for half-yearly compounding.', formulaIds: ['compound-interest'], tags: ['Compound interest', 'Half-yearly'] });
  }
};

const motionBuilders = {
  'time-work': i => {
    const a = 8 + i % 3 * 2; const b = 12 + i % 3 * 3;
    if (i % 5 === 0) { const answer = a * b / (a + b); return q('time-work', i, { prompt: `A can finish a job in ${a} days and B in ${b} days. How long do they take together?`, answer: `${format(answer)} days`, wrong: [`${a + b} days`, `${format((a + b) / 2)} days`, `${format(answer + 1)} days`], explanation: `Combined rate = 1/${a}+1/${b}=(${a + b})/${a * b}; time = ${a * b}/${a + b} = ${format(answer)} days.`, shortcut: 'For two workers, combined time = ab/(a+b).', formulaIds: ['time-work'], tags: ['Time & work', 'Combined work'] }); }
    if (i % 5 === 1) { const days = 15; const done = 6; const answer = 1 - done / days; return q('time-work', i, { prompt: `A can finish work in ${days} days. What fraction remains after ${done} days of work?`, answer: fraction(days - done, days), wrong: [fraction(done, days), fraction(1, days), `${days - done}/${done}`], explanation: `A completes ${done}/${days}; remaining work = 1−${done}/${days} = ${days - done}/${days}.`, shortcut: 'One day’s work is 1/total days.', formulaIds: ['time-work'], tags: ['Time & work', 'Fraction of work'] }); }
    if (i % 5 === 2) { const aDays = 12; const bDays = 18; const worked = 3; const remaining = 1 - worked / aDays; const answer = remaining / (1 / aDays + 1 / bDays); return q('time-work', i, { prompt: `A works alone for ${worked} days on a job he can finish in ${aDays} days. B, who can finish it in ${bDays} days, joins A. How many more days are needed?`, answer: `${format(answer)} days`, wrong: ['6 days', '9 days', '12 days'], explanation: `A completes ${worked}/${aDays}=1/4. Remaining = 3/4. Together their rate is 1/12+1/18=5/36, so time = (3/4)/(5/36)=5.4 days.`, shortcut: 'First subtract completed work, then use the combined rate.', formulaIds: ['time-work'], tags: ['Time & work', 'Joining work'] }); }
    if (i % 5 === 3) { const aDays = 10; const bDays = 15; const answer = 1 / aDays - 1 / bDays; return q('time-work', i, { prompt: `A finishes a job in ${aDays} days and B in ${bDays} days. What fraction more work does A do than B per day?`, answer: fraction(1, 30), wrong: [fraction(1, 10), fraction(1, 15), fraction(1, 25)], explanation: `Difference in rates = 1/10−1/15 = (3−2)/30 = 1/30.`, shortcut: 'Subtract rates after taking a common denominator.', formulaIds: ['time-work'], tags: ['Time & work', 'Work rate'] }); }
    const increase = 25; const original = 20; const answer = original / (1 + increase / 100); return q('time-work', i, { prompt: `A worker becomes ${increase}% more efficient. If the old job time was ${original} days, what is the new time?`, answer: `${answer} days`, wrong: ['15 days', '25 days', '16 days'], explanation: `Time is inversely proportional to efficiency. New time = ${original}/1.25 = ${answer} days.`, shortcut: 'Efficiency up by r% means time is divided by 1+r/100.', formulaIds: ['time-work'], tags: ['Efficiency', 'Inverse proportion'] });
  },
  'work-wages': i => {
    if (i % 5 === 0) return q('work-wages', i, { prompt: 'A and B are paid in the ratio 3:2 for the same job. If B receives ₹800, what does A receive?', answer: '₹1200', wrong: ['₹1000', '₹1600', '₹800'], explanation: `One ratio part is ₹400. A has 3 parts, so receives ₹1200.`, shortcut: 'Wages follow the given work ratio.', formulaIds: ['partnership'], tags: ['Wages', 'Ratio'] });
    if (i % 5 === 1) return q('work-wages', i, { prompt: 'A can do a job in 10 days and B in 15 days. They earn ₹5000 in proportion to work done. What is A’s share?', answer: '₹3000', wrong: ['₹2500', '₹2000', '₹3500'], explanation: `Daily work ratio A:B = 1/10:1/15 = 3:2. A gets 3/5 of ₹5000 = ₹3000.`, shortcut: 'For equal time, wage ratio equals work-rate ratio.', formulaIds: ['time-work', 'partnership'], tags: ['Wages', 'Work rate'] });
    if (i % 5 === 2) return q('work-wages', i, { prompt: 'A is 50% more efficient than B. If B earns ₹600 for equal time, A should earn:', answer: '₹900', wrong: ['₹750', '₹1200', '₹600'], explanation: `Equal time means wages follow output. A:B = 150:100 = 3:2, so A earns ₹900.`, shortcut: 'Convert “50% more” to the ratio 3:2.', formulaIds: ['time-work'], tags: ['Wages', 'Efficiency'] });
    if (i % 5 === 3) return q('work-wages', i, { prompt: 'A and B together complete a job. A works 6 days at 4 units/day and B works 4 days at 6 units/day. If wages total ₹2400, A’s share is:', answer: '₹1200', wrong: ['₹1440', '₹960', '₹1500'], explanation: `A does 24 units and B does 24 units. Equal work earns equal wages: ₹1200 each.`, shortcut: 'Calculate actual output before splitting wages.', formulaIds: ['partnership'], tags: ['Wages', 'Output'] });
    return q('work-wages', i, { prompt: 'A completes 60% of a job and B completes the rest. If total wages are ₹3500, B receives:', answer: '₹1400', wrong: ['₹2100', '₹1750', '₹1500'], explanation: `B completes 40%, so B’s wage = 40% of ₹3500 = ₹1400.`, shortcut: 'Wages are proportional to completed work.', formulaIds: ['partnership', 'percentage-change'], tags: ['Wages', 'Percentage'] });
  },
  'pipes-cisterns': i => {
    if (i % 5 === 0) return q('pipes-cisterns', i, { prompt: 'Pipe A fills a tank in 6 hours and pipe B fills it in 3 hours. How long together?', answer: '2 hours', wrong: ['4 hours', '9 hours', '1.5 hours'], explanation: `Rate = 1/6+1/3=1/2 tank/hour. One tank takes 2 hours.`, shortcut: 'Use the same work-rate method as Time & Work.', formulaIds: ['pipes'], tags: ['Pipes', 'Combined rate'] });
    if (i % 5 === 1) return q('pipes-cisterns', i, { prompt: 'A pipe fills a tank in 8 hours while a leak empties it in 24 hours. How long with both open?', answer: '12 hours', wrong: ['6 hours', '16 hours', '32 hours'], explanation: `Net rate = 1/8−1/24=2/24=1/12.`, shortcut: 'An outlet has a negative rate.', formulaIds: ['pipes'], tags: ['Pipes', 'Leak'] });
    if (i % 5 === 2) return q('pipes-cisterns', i, { prompt: 'A fills a tank in 12 hours. After 3 hours, a second pipe that fills it in 6 hours is opened. How many more hours are needed?', answer: '3 hours', wrong: ['4.5 hours', '6 hours', '2 hours'], explanation: `A fills 1/4 in 3 hours; 3/4 remains. Together, rate = 1/12+1/6=1/4, so 3 hours.`, shortcut: 'Calculate what was filled before the second pipe opens.', formulaIds: ['pipes'], tags: ['Pipes', 'Joining later'] });
    if (i % 5 === 3) return q('pipes-cisterns', i, { prompt: 'Two identical pipes fill a tank in 5 hours together. How long does one pipe take?', answer: '10 hours', wrong: ['5 hours', '2.5 hours', '15 hours'], explanation: `Each pipe contributes half the combined rate, so one needs twice the time: 10 hours.`, shortcut: 'Identical workers/pipes: one takes twice their combined time.', formulaIds: ['pipes'], tags: ['Pipes', 'Identical rates'] });
    return q('pipes-cisterns', i, { prompt: 'Pipe A fills a tank in 10 hours. A leak can empty it in 15 hours. If both operate for 6 hours, what fraction of the tank is filled?', answer: '1/5', wrong: ['2/5', '3/5', '1/2'], explanation: `Net rate = 1/10−1/15=1/30. In 6 hours, filled = 6/30=1/5.`, shortcut: 'Multiply net rate by the time open.', formulaIds: ['pipes'], tags: ['Pipes', 'Leak', 'Fraction'] });
  },
  'speed-distance-time': i => {
    if (i % 5 === 0) return q('speed-distance-time', i, { prompt: 'A car travels equal distances at 40 km/h and 60 km/h. What is its average speed?', answer: '48 km/h', wrong: ['50 km/h', '45 km/h', '40 km/h'], explanation: `For equal distances, average speed = 2ab/(a+b) = 2×40×60/100 = 48 km/h.`, shortcut: 'Equal distances use harmonic mean, not ordinary mean.', formulaIds: ['speed-distance-time'], tags: ['Average speed', 'Equal distance'] });
    if (i % 5 === 1) return q('speed-distance-time', i, { prompt: 'A 180 km trip takes 3 hours. To finish it in 2.5 hours, the speed must increase by:', answer: '12 km/h', wrong: ['10 km/h', '18 km/h', '20 km/h'], explanation: `Current speed = 60 km/h; required speed = 72 km/h. Increase = 12 km/h.`, shortcut: 'Find both speeds from the same distance.', formulaIds: ['speed-distance-time'], tags: ['Speed', 'Time'] });
    if (i % 5 === 2) return q('speed-distance-time', i, { prompt: 'Two cyclists start 150 km apart and ride toward each other at 20 km/h and 30 km/h. When do they meet?', answer: '3 hours', wrong: ['5 hours', '2.5 hours', '4 hours'], explanation: `Relative speed = 20+30=50 km/h. Time = 150/50=3 hours.`, shortcut: 'For opposite directions, add speeds.', formulaIds: ['speed-distance-time'], tags: ['Relative speed'] });
    if (i % 5 === 3) return q('speed-distance-time', i, { prompt: 'Walking at 5 km/h, a person is 12 minutes late. At 6 km/h, they are 8 minutes early. What is the distance?', answer: '10 km', wrong: ['8 km', '12 km', '6 km'], explanation: `Time difference is 20 min = 1/3 h. D(1/5−1/6)=1/3, so D/30=1/3 and D=10 km.`, shortcut: 'Use the difference between the two travel times.', formulaIds: ['speed-distance-time'], tags: ['Speed', 'Late/early', 'Equation'] });
    return q('speed-distance-time', i, { prompt: 'A man covers half a journey at 30 km/h and the other half at 45 km/h. The average speed is:', answer: '36 km/h', wrong: ['37.5 km/h', '40 km/h', '30 km/h'], explanation: `Equal-distance average = 2×30×45/(30+45)=36 km/h.`, shortcut: 'Use 2ab/(a+b) for equal halves.', formulaIds: ['speed-distance-time'], tags: ['Average speed'] });
  },
  trains: i => {
    if (i % 5 === 0) return q('trains', i, { prompt: 'A 180 m train moves at 54 km/h. How long to cross a pole?', answer: '12 seconds', wrong: ['10 seconds', '15 seconds', '18 seconds'], explanation: `54 km/h = 15 m/s. Time = 180/15 = 12 s.`, shortcut: 'Convert km/h to m/s by multiplying by 5/18.', formulaIds: ['trains'], tags: ['Train', 'Pole'] });
    if (i % 5 === 1) return q('trains', i, { prompt: 'A 150 m train at 72 km/h crosses a 250 m platform in:', answer: '20 seconds', wrong: ['12.5 seconds', '18 seconds', '25 seconds'], explanation: `Total distance = 150+250=400 m; 72 km/h=20 m/s. Time=20 s.`, shortcut: 'For a platform, add train and platform lengths.', formulaIds: ['trains'], tags: ['Train', 'Platform'] });
    if (i % 5 === 2) return q('trains', i, { prompt: 'Two 120 m trains run in opposite directions at 54 km/h and 36 km/h. How long to cross each other?', answer: '9.6 seconds', wrong: ['12 seconds', '8 seconds', '16 seconds'], explanation: `Relative speed = 90 km/h=25 m/s. Distance=240 m, so time=240/25=9.6 s.`, shortcut: 'Opposite directions: add speeds and lengths.', formulaIds: ['trains'], tags: ['Train', 'Relative speed'] });
    if (i % 5 === 3) return q('trains', i, { prompt: 'A train passes a man walking at 6 km/h in the same direction in 18 seconds. The train is 120 m long. Find the train speed.', answer: '30 km/h', wrong: ['24 km/h', '36 km/h', '20 km/h'], explanation: `Relative speed = 120/18=6.67 m/s=24 km/h. Train speed = 24+6=30 km/h.`, shortcut: 'Same direction: train speed minus person speed.', formulaIds: ['trains'], tags: ['Train', 'Relative speed'] });
    return q('trains', i, { prompt: 'A train crosses a 300 m bridge in 30 seconds at 54 km/h. What is the train length?', answer: '150 m', wrong: ['300 m', '450 m', '120 m'], explanation: `At 15 m/s, total distance in 30 s=450 m. Subtract bridge length: 150 m.`, shortcut: 'Distance covered = train length + bridge length.', formulaIds: ['trains'], tags: ['Train', 'Bridge'] });
  },
  'boats-streams': i => {
    if (i % 5 === 0) return q('boats-streams', i, { prompt: 'A boat travels 36 km downstream in 3 h and upstream in 6 h. What is its still-water speed?', answer: '9 km/h', wrong: ['6 km/h', '12 km/h', '3 km/h'], explanation: `Downstream=12, upstream=6. Still-water speed=(12+6)/2=9 km/h.`, shortcut: 'Average downstream and upstream speeds to get boat speed.', formulaIds: ['boats-streams'], tags: ['Boat', 'Stream'] });
    if (i % 5 === 1) return q('boats-streams', i, { prompt: 'A boat’s still-water speed is 10 km/h and stream speed is 2 km/h. How long for 24 km upstream?', answer: '3 hours', wrong: ['2 hours', '2.4 hours', '4 hours'], explanation: `Upstream speed=10−2=8 km/h. Time=24/8=3 h.`, shortcut: 'Subtract stream speed for upstream travel.', formulaIds: ['boats-streams'], tags: ['Boat', 'Upstream'] });
    if (i % 5 === 2) return q('boats-streams', i, { prompt: 'A boat takes 2 h downstream and 3 h upstream for the same distance. The stream speed is 2 km/h. Still-water speed is:', answer: '10 km/h', wrong: ['8 km/h', '12 km/h', '6 km/h'], explanation: `Let distance D. D/2=b+2 and D/3=b−2. Solving gives b=10.`, shortcut: 'For equal distances, speed ratios are inverse of time ratios.', formulaIds: ['boats-streams'], tags: ['Boat', 'Equation'] });
    if (i % 5 === 3) return q('boats-streams', i, { prompt: 'A raft travels 18 km in 6 h. What is the stream speed?', answer: '3 km/h', wrong: ['6 km/h', '9 km/h', '2 km/h'], explanation: `A raft has no still-water speed, so it moves at stream speed: 18/6=3 km/h.`, shortcut: 'Raft speed equals stream speed.', formulaIds: ['boats-streams'], tags: ['Raft', 'Stream'] });
    return q('boats-streams', i, { prompt: 'A boat travels 30 km downstream and returns upstream in 7.5 h total. If its still-water speed is 9 km/h, stream speed is:', answer: '3 km/h', wrong: ['2 km/h', '4 km/h', '6 km/h'], explanation: `With stream speed 3, downstream/upstream speeds are 12 and 6. Times are 30/12=2.5 h and 30/6=5 h, totaling 7.5 h.`, shortcut: 'Test the two travel times against the round-trip total.', formulaIds: ['boats-streams'], tags: ['Boat', 'Round trip'] });
  },
  races: i => {
    if (i % 5 === 0) return q('races', i, { prompt: 'In a 100 m race, A beats B by 20 m. If A takes 10 s, B’s time is:', answer: '12.5 seconds', wrong: ['10 seconds', '8 seconds', '15 seconds'], explanation: `When A finishes 100 m, B covers 80 m. B’s time for 100 m = 10×100/80=12.5 s.`, shortcut: 'Distance ratio at the finish equals speed ratio.', formulaIds: ['speed-distance-time'], tags: ['Race', 'Speed ratio'] });
    if (i % 5 === 1) return q('races', i, { prompt: 'A can give B a 20 m start in a 100 m race. What is A:B speed ratio?', answer: '5:4', wrong: ['4:5', '6:5', '1:1'], explanation: `A runs 100 m while B runs 80 m in the same time, so ratio=100:80=5:4.`, shortcut: 'Same time means distance ratio is speed ratio.', formulaIds: ['speed-distance-time'], tags: ['Race', 'Head start'] });
    if (i % 5 === 2) return q('races', i, { prompt: 'A beats B by 10 seconds in a race. A finishes in 50 seconds. By what percent is B slower than A?', answer: '20%', wrong: ['16.67%', '25%', '10%'], explanation: `B takes 60 s. Relative to A’s 50 s, excess time =10/50=20%.`, shortcut: 'Read “slower” carefully: this asks the time increase relative to A.', formulaIds: ['percentage-change'], tags: ['Race', 'Percentage'] });
    if (i % 5 === 3) return q('races', i, { prompt: 'A gives B a 10% head start. If B runs at 90% of A’s speed, who wins a 100 m race?', answer: 'They tie', wrong: ['A wins', 'B wins', 'Cannot be determined'], explanation: `B runs 90 m at 90% of A’s speed, taking the same time A takes for 100 m.`, shortcut: 'Compare each runner’s remaining distance divided by speed.', formulaIds: ['speed-distance-time'], tags: ['Race', 'Head start'] });
    return q('races', i, { prompt: 'In a 400 m race, A finishes in 50 s and B in 60 s. By how many metres does A beat B?', answer: '66.67 m', wrong: ['80 m', '50 m', '60 m'], explanation: `In 50 s, B covers 400×50/60=333.33 m. Margin=66.67 m.`, shortcut: 'Find the losing runner’s distance at the winner’s finishing time.', formulaIds: ['speed-distance-time'], tags: ['Race', 'Margin'] });
  }
};

const algebraBuilders = {
  'number-system': i => {
    if (i % 5 === 0) return q('number-system', i, { prompt: 'What is the remainder when 7³ is divided by 5?', answer: '3', wrong: ['2', '1', '4'], explanation: `7 leaves remainder 2 when divided by 5. 2³=8 leaves remainder 3.`, shortcut: 'Reduce the base modulo the divisor before taking powers.', formulaIds: ['number-system'], tags: ['Remainder', 'Powers'] });
    if (i % 5 === 1) return q('number-system', i, { prompt: 'Which smallest number must be added to 999 to make it divisible by 17?', answer: '4', wrong: ['1', '8', '17'], explanation: `999 ÷17 leaves remainder 13. Add 4 to reach the next multiple, 1003.`, shortcut: 'Add divisor minus remainder.', formulaIds: ['number-system'], tags: ['Divisibility', 'Remainder'] });
    if (i % 5 === 2) return q('number-system', i, { prompt: 'How many factors does 360 have?', answer: '24', wrong: ['18', '30', '36'], explanation: `360=2³×3²×5¹. Number of factors=(3+1)(2+1)(1+1)=24.`, shortcut: 'Add one to each prime exponent and multiply.', formulaIds: ['number-system'], tags: ['Factors', 'Prime factorisation'] });
    if (i % 5 === 3) return q('number-system', i, { prompt: 'The unit digit of 3⁴⁷ is:', answer: '7', wrong: ['3', '9', '1'], explanation: `Units digits of powers of 3 repeat 3,9,7,1. 47 leaves remainder 3 on division by 4, so the digit is 7.`, shortcut: 'Use the four-term cycle of powers of 3.', formulaIds: ['number-system'], tags: ['Unit digit', 'Cyclic pattern'] });
    return q('number-system', i, { prompt: 'What is the least number that leaves remainder 2 when divided by 3, 4 and 5?', answer: '62', wrong: ['2', '60', '59'], explanation: `The number is 2 more than a common multiple of 3,4,5. LCM=60, so 62.`, shortcut: 'Same remainder: subtract it, take the LCM, then add it back.', formulaIds: ['number-system', 'lcm-hcf'], tags: ['Remainder', 'LCM'] });
  },
  'lcm-hcf': i => {
    if (i % 5 === 0) return q('lcm-hcf', i, { prompt: 'Find the HCF of 84 and 126.', answer: '42', wrong: ['6', '21', '252'], explanation: `84=2²×3×7 and 126=2×3²×7. Common factors give 2×3×7=42.`, shortcut: 'Use only the lowest common prime powers.', formulaIds: ['lcm-hcf'], tags: ['HCF', 'Prime factors'] });
    if (i % 5 === 1) return q('lcm-hcf', i, { prompt: 'Find the LCM of 12, 18 and 30.', answer: '180', wrong: ['60', '90', '360'], explanation: `Highest powers are 2²,3² and 5, so LCM=4×9×5=180.`, shortcut: 'Use the highest power of each required prime.', formulaIds: ['lcm-hcf'], tags: ['LCM', 'Prime factors'] });
    if (i % 5 === 2) return q('lcm-hcf', i, { prompt: 'Two numbers have HCF 6 and LCM 180. If one number is 30, the other is:', answer: '36', wrong: ['6', '60', '150'], explanation: `Product of two numbers=HCF×LCM=1080. Other=1080/30=36.`, shortcut: 'For two numbers, product = HCF × LCM.', formulaIds: ['lcm-hcf'], tags: ['LCM', 'HCF', 'Product'] });
    if (i % 5 === 3) return q('lcm-hcf', i, { prompt: 'What is the greatest number that divides 125, 185 and 245 leaving the same remainder?', answer: '60', wrong: ['5', '30', '120'], explanation: `Take HCF of differences: 185−125=60 and 245−185=60.`, shortcut: 'Same remainder means the divisor divides every pairwise difference.', formulaIds: ['lcm-hcf'], tags: ['HCF', 'Remainder'] });
    return q('lcm-hcf', i, { prompt: 'Three bells ring at intervals of 6, 8 and 12 minutes. If they ring now, when do they next ring together?', answer: '24 minutes', wrong: ['12 minutes', '26 minutes', '48 minutes'], explanation: `The next common ringing time is LCM(6,8,12)=24 minutes.`, shortcut: 'Recurring simultaneous events use LCM.', formulaIds: ['lcm-hcf'], tags: ['LCM', 'Application'] });
  },
  simplification: i => {
    if (i % 5 === 0) return q('simplification', i, { prompt: 'Evaluate: 25% of 64 + 3² × 4.', answer: '52', wrong: ['100', '40', '28'], explanation: `25% of 64=16 and 3²×4=36; total=52.`, shortcut: 'Apply powers and multiplication before addition.', formulaIds: ['percentage-change'], tags: ['BODMAS', 'Percentage'] });
    if (i % 5 === 1) return q('simplification', i, { prompt: 'Simplify: (3/4 of 48) ÷ 6 + 5.', answer: '11', wrong: ['6', '36', '13'], explanation: `3/4 of 48=36; 36÷6=6; 6+5=11.`, shortcut: '“Of” means multiplication and is evaluated before division/addition.', formulaIds: ['percentage-change'], tags: ['Fractions', 'BODMAS'] });
    if (i % 5 === 2) return q('simplification', i, { prompt: 'Evaluate: 0.25 × 0.4 ÷ 0.05.', answer: '2', wrong: ['0.02', '20', '0.2'], explanation: `0.25×0.4=0.1; 0.1÷0.05=2.`, shortcut: 'Shift decimal places or convert decimals to fractions.', formulaIds: ['percentage-change'], tags: ['Decimals', 'Simplification'] });
    if (i % 5 === 3) return q('simplification', i, { prompt: 'Simplify: √196 + ∛125 − 2³.', answer: '11', wrong: ['19', '6', '3'], explanation: `√196=14, ∛125=5 and 2³=8. Thus 14+5−8=11.`, shortcut: 'Evaluate roots and powers before the remaining operations.', formulaIds: ['percentage-change'], tags: ['Roots', 'Powers'] });
    return q('simplification', i, { prompt: 'If x = 0.2, find (x² + x) / x.', answer: '1.2', wrong: ['0.24', '0.2', '2'], explanation: `(x²+x)/x = x+1 = 1.2, because x is non-zero.`, shortcut: 'Factor out x before substituting decimals.', formulaIds: ['percentage-change'], tags: ['Algebraic simplification'] });
  },
  algebra: i => {
    if (i % 5 === 0) return q('algebra', i, { prompt: 'If 3x − 7 = 20, x equals:', answer: '9', wrong: ['7', '13', '27'], explanation: `3x=27, so x=9.`, shortcut: 'Undo addition/subtraction before division.', formulaIds: ['percentage-change'], tags: ['Linear equation'] });
    if (i % 5 === 1) return q('algebra', i, { prompt: 'If x + y = 12 and xy = 35, what is x² + y²?', answer: '74', wrong: ['144', '70', '109'], explanation: `x²+y²=(x+y)²−2xy=144−70=74.`, shortcut: 'Use identities instead of finding x and y separately.', formulaIds: ['percentage-change'], tags: ['Algebraic identity'] });
    if (i % 5 === 2) return q('algebra', i, { prompt: 'The roots of x² − 7x + 12 = 0 are:', answer: '3 and 4', wrong: ['2 and 6', '−3 and −4', '1 and 12'], explanation: `Find factors of 12 that add to 7: 3 and 4.`, shortcut: 'For x²−sx+p, seek factors of p that sum to s.', formulaIds: ['percentage-change'], tags: ['Quadratic equation'] });
    if (i % 5 === 3) return q('algebra', i, { prompt: 'If a − b = 4 and ab = 21, find a² + b².', answer: '58', wrong: ['16', '42', '100'], explanation: `(a−b)²=a²+b²−2ab. Thus a²+b²=16+42=58.`, shortcut: 'Square the known sum or difference identity.', formulaIds: ['percentage-change'], tags: ['Algebraic identity'] });
    return q('algebra', i, { prompt: 'A number is increased by 20% and then decreased by 20%. The algebraic net change is:', answer: '4% decrease', wrong: ['No change', '4% increase', '20% decrease'], explanation: `1.2×0.8=0.96, so final value is 96% of original: a 4% decrease.`, shortcut: 'Use multipliers rather than cancelling percentages.', formulaIds: ['percentage-change'], tags: ['Algebra', 'Percentage'] });
  },
  progressions: i => {
    if (i % 5 === 0) return q('progressions', i, { prompt: 'Find the 20th term of the AP 3, 7, 11, …', answer: '79', wrong: ['83', '76', '80'], explanation: `a=3,d=4. a₂₀=3+19×4=79.`, shortcut: 'The nth term uses n−1 differences.', formulaIds: ['progressions'], tags: ['AP', 'Nth term'] });
    if (i % 5 === 1) return q('progressions', i, { prompt: 'What is the sum of the first 10 terms of 2, 5, 8, …?', answer: '155', wrong: ['145', '170', '50'], explanation: `a=2,d=3; tenth term=29. Sum=10/2×(2+29)=155.`, shortcut: 'Find the last term, then use n/2(first+last).', formulaIds: ['progressions'], tags: ['AP', 'Sum'] });
    if (i % 5 === 2) return q('progressions', i, { prompt: 'The 5th term of a GP is 48 and common ratio is 2. The first term is:', answer: '3', wrong: ['6', '12', '24'], explanation: `ar⁴=48; a=48/16=3.`, shortcut: 'Move backward by dividing by the common ratio.', formulaIds: ['progressions'], tags: ['GP', 'Nth term'] });
    if (i % 5 === 3) return q('progressions', i, { prompt: 'Insert one arithmetic mean between 8 and 20.', answer: '14', wrong: ['12', '16', '10'], explanation: `8, x, 20 is an AP, so x=(8+20)/2=14.`, shortcut: 'A single arithmetic mean is the ordinary average.', formulaIds: ['progressions', 'average'], tags: ['AP', 'Mean'] });
    return q('progressions', i, { prompt: 'In an AP, the 8th term is 31 and the 15th term is 59. What is the common difference?', answer: '4', wrong: ['7', '28', '3'], explanation: `The term difference is 59−31=28 across 7 steps, so d=4.`, shortcut: 'Subtract terms and divide by the difference in their indices.', formulaIds: ['progressions'], tags: ['AP', 'Common difference'] });
  },
  logarithms: i => {
    if (i % 5 === 0) return q('logarithms', i, { prompt: 'Find log₂ 32.', answer: '5', wrong: ['4', '16', '32'], explanation: `2⁵=32, so log₂32=5.`, shortcut: 'Rewrite the logarithm as an exponent.', formulaIds: ['logarithms'], tags: ['Logarithm', 'Exponent'] });
    if (i % 5 === 1) return q('logarithms', i, { prompt: 'If log₁₀2 = 0.3010, then log₁₀20 is:', answer: '1.3010', wrong: ['0.6020', '2.3010', '1.6990'], explanation: `20=2×10, so log20=log2+log10=0.3010+1=1.3010.`, shortcut: 'Separate a product using log(ab)=log a+log b.', formulaIds: ['logarithms'], tags: ['Logarithm', 'Product rule'] });
    if (i % 5 === 2) return q('logarithms', i, { prompt: 'Solve: log₃x = 4.', answer: '81', wrong: ['12', '64', '27'], explanation: `x=3⁴=81.`, shortcut: 'Convert log form directly to exponential form.', formulaIds: ['logarithms'], tags: ['Logarithm', 'Equation'] });
    if (i % 5 === 3) return q('logarithms', i, { prompt: 'log₅125 + log₅5 equals:', answer: '4', wrong: ['3', '5', '625'], explanation: `log₅125=3 and log₅5=1; sum=4.`, shortcut: 'Recognise exact powers before applying rules.', formulaIds: ['logarithms'], tags: ['Logarithm', 'Addition'] });
    return q('logarithms', i, { prompt: 'If logₐ27 = 3, a is:', answer: '3', wrong: ['9', '27', '1/3'], explanation: `a³=27, so a=3.`, shortcut: 'The base raised to the log value equals the argument.', formulaIds: ['logarithms'], tags: ['Logarithm', 'Base'] });
  },
  'permutation-combination': i => {
    if (i % 5 === 0) return q('permutation-combination', i, { prompt: 'How many 3-member committees can be chosen from 8 students?', answer: '56', wrong: ['336', '24', '64'], explanation: `Order does not matter: 8C3=8×7×6/6=56.`, shortcut: 'Committee/selection means combination.', formulaIds: ['permutation-combination'], tags: ['Combination', 'Committee'] });
    if (i % 5 === 1) return q('permutation-combination', i, { prompt: 'In how many ways can 5 distinct books be arranged on a shelf?', answer: '120', wrong: ['25', '60', '10'], explanation: `All 5 positions are ordered: 5!=120.`, shortcut: 'Arrangement of all distinct items is n!.', formulaIds: ['permutation-combination'], tags: ['Permutation', 'Arrangement'] });
    if (i % 5 === 2) return q('permutation-combination', i, { prompt: 'How many 4-letter arrangements can be made from A, B, C, D, E without repetition?', answer: '120', wrong: ['5', '24', '625'], explanation: `5P4=5×4×3×2=120.`, shortcut: 'Order matters and no repeats: use nPr.', formulaIds: ['permutation-combination'], tags: ['Permutation'] });
    if (i % 5 === 3) return q('permutation-combination', i, { prompt: 'How many ways can a captain and vice-captain be selected from 10 players?', answer: '90', wrong: ['45', '100', '720'], explanation: `The roles differ, so 10P2=10×9=90.`, shortcut: 'Different posts make order matter.', formulaIds: ['permutation-combination'], tags: ['Permutation', 'Roles'] });
    return q('permutation-combination', i, { prompt: 'How many diagonals does a hexagon have?', answer: '9', wrong: ['6', '12', '15'], explanation: `Choose any two vertices: 6C2=15 sides/diagonals; subtract 6 sides to get 9 diagonals.`, shortcut: 'Diagonals in n-gon = nC2−n.', formulaIds: ['permutation-combination'], tags: ['Combination', 'Geometry'] });
  },
  probability: i => {
    if (i % 5 === 0) return q('probability', i, { prompt: 'A fair die is rolled. What is the probability of a prime number?', answer: '1/2', wrong: ['1/3', '2/3', '5/6'], explanation: `Prime faces are 2,3,5: 3 favourable out of 6, or 1/2.`, shortcut: 'List outcomes before counting them.', formulaIds: ['probability'], tags: ['Probability', 'Die'] });
    if (i % 5 === 1) return q('probability', i, { prompt: 'A bag has 3 red and 2 blue balls. Two are drawn without replacement. Probability both are red?', answer: '3/10', wrong: ['9/25', '3/5', '1/2'], explanation: `3/5×2/4=6/20=3/10.`, shortcut: 'Without replacement, decrease both numerator and denominator.', formulaIds: ['probability'], tags: ['Probability', 'Without replacement'] });
    if (i % 5 === 2) return q('probability', i, { prompt: 'Two fair coins are tossed. Probability of at least one head?', answer: '3/4', wrong: ['1/4', '1/2', '1'], explanation: `Use complement: P(no head)=P(TT)=1/4; desired=3/4.`, shortcut: '“At least one” is often easiest through its complement.', formulaIds: ['probability'], tags: ['Probability', 'Complement'] });
    if (i % 5 === 3) return q('probability', i, { prompt: 'One card is drawn from a standard deck. Probability it is a heart or a king?', answer: '4/13', wrong: ['17/52', '1/4', '1/13'], explanation: `13 hearts + 4 kings − 1 king of hearts =16; 16/52=4/13.`, shortcut: 'For “or”, add and subtract the overlap.', formulaIds: ['probability'], tags: ['Probability', 'Cards', 'Union'] });
    return q('probability', i, { prompt: 'A number is chosen at random from 1 to 20. Probability it is divisible by 2 or 3?', answer: '13/20', wrong: ['10/20', '6/20', '16/20'], explanation: `Multiples of 2:10; of 3:6; overlap multiples of 6:3. Total=10+6−3=13.`, shortcut: 'Use inclusion-exclusion for overlapping conditions.', formulaIds: ['probability'], tags: ['Probability', 'Inclusion-exclusion'] });
  }
};

const geometryBuilders = {
  geometry: i => {
    if (i % 5 === 0) return q('geometry', i, { prompt: 'Two angles of a triangle are 48° and 67°. The third angle is:', answer: '65°', wrong: ['75°', '115°', '55°'], explanation: `Triangle angles sum to 180°. Third angle=180−48−67=65°.`, shortcut: 'Triangle interior angles always total 180°.', formulaIds: ['geometry'], tags: ['Geometry', 'Triangle'] });
    if (i % 5 === 1) return q('geometry', i, { prompt: 'An exterior angle of a triangle is 120° and one opposite interior angle is 45°. The other opposite interior angle is:', answer: '75°', wrong: ['60°', '45°', '135°'], explanation: `Exterior angle equals the sum of two remote interior angles. Other=120−45=75°.`, shortcut: 'Exterior angle equals the two non-adjacent interior angles combined.', formulaIds: ['geometry'], tags: ['Geometry', 'Triangle'] });
    if (i % 5 === 2) return q('geometry', i, { prompt: 'A right triangle has legs 6 cm and 8 cm. Its hypotenuse is:', answer: '10 cm', wrong: ['14 cm', '12 cm', '7 cm'], explanation: `By Pythagoras, √(6²+8²)=√100=10 cm.`, shortcut: 'Recognise the 3:4:5 triangle scaled by 2.', formulaIds: ['geometry'], tags: ['Geometry', 'Pythagoras'] });
    if (i % 5 === 3) return q('geometry', i, { prompt: 'The radius to a point of tangency is always:', answer: 'Perpendicular to the tangent', wrong: ['Parallel to the tangent', 'Equal to the tangent', 'Bisects the tangent'], explanation: `A tangent touches a circle at one point and is perpendicular to the radius drawn there.`, shortcut: 'Radius–tangent angle is 90°.', formulaIds: ['geometry'], tags: ['Geometry', 'Circle'] });
    return q('geometry', i, { prompt: 'The angles of a quadrilateral are in ratio 1:2:3:4. The largest angle is:', answer: '144°', wrong: ['108°', '120°', '72°'], explanation: `Quadrilateral sum=360°. Ten parts mean 36° each; largest=4×36=144°.`, shortcut: 'Find one ratio part from the total angle sum.', formulaIds: ['geometry', 'ratio-share'], tags: ['Geometry', 'Quadrilateral', 'Ratio'] });
  },
  mensuration: i => {
    if (i % 5 === 0) return q('mensuration', i, { prompt: 'Find the area of a circle of radius 7 cm using π=22/7.', answer: '154 cm²', wrong: ['44 cm²', '308 cm²', '49 cm²'], explanation: `Area=πr²=22/7×49=154 cm².`, shortcut: 'Use 22/7 comfortably when radius is a multiple of 7.', formulaIds: ['mensuration'], tags: ['Mensuration', 'Circle'] });
    if (i % 5 === 1) return q('mensuration', i, { prompt: 'A rectangle has perimeter 50 cm and length 15 cm. Its area is:', answer: '150 cm²', wrong: ['125 cm²', '250 cm²', '100 cm²'], explanation: `2(l+b)=50 gives b=10. Area=15×10=150 cm².`, shortcut: 'Find the missing breadth from the half-perimeter.', formulaIds: ['mensuration'], tags: ['Mensuration', 'Rectangle'] });
    if (i % 5 === 2) return q('mensuration', i, { prompt: 'The volume of a cylinder with r=7 cm and h=10 cm is, using π=22/7:', answer: '1540 cm³', wrong: ['748 cm³', '440 cm³', '3080 cm³'], explanation: `Volume=πr²h=22/7×49×10=1540 cm³.`, shortcut: 'Area of circular base × height.', formulaIds: ['mensuration'], tags: ['Mensuration', 'Cylinder'] });
    if (i % 5 === 3) return q('mensuration', i, { prompt: 'A cube’s volume is 343 cm³. Its total surface area is:', answer: '294 cm²', wrong: ['147 cm²', '1029 cm²', '49 cm²'], explanation: `Side=∛343=7. TSA=6×7²=294 cm².`, shortcut: 'Find side from the cube root before surface area.', formulaIds: ['mensuration'], tags: ['Mensuration', 'Cube'] });
    return q('mensuration', i, { prompt: 'A cone and a cylinder have the same base radius and height. The cone volume is what fraction of the cylinder volume?', answer: '1/3', wrong: ['1/2', '2/3', '3'], explanation: `Cone volume=1/3πr²h while cylinder volume=πr²h.`, shortcut: 'A cone is one-third of the matching cylinder.', formulaIds: ['mensuration'], tags: ['Mensuration', 'Cone', 'Cylinder'] });
  },
  clocks: i => {
    if (i % 5 === 0) return q('clocks', i, { prompt: 'What is the angle between clock hands at 3:00?', answer: '90°', wrong: ['60°', '75°', '120°'], explanation: `Minute hand is at 12; hour hand at 3, which is 3×30°=90°.`, shortcut: 'Each hour mark is 30°.', formulaIds: ['clocks'], tags: ['Clock', 'Angle'] });
    if (i % 5 === 1) return q('clocks', i, { prompt: 'What is the smaller angle between the hands at 6:00?', answer: '180°', wrong: ['0°', '90°', '150°'], explanation: `Hands point to 12 and 6, opposite directions: 180°.`, shortcut: 'At exact hours, hour hand sits on the hour number.', formulaIds: ['clocks'], tags: ['Clock', 'Angle'] });
    if (i % 5 === 2) return q('clocks', i, { prompt: 'At 2:20, the minute hand is at 120°. The hour hand is at:', answer: '70°', wrong: ['60°', '80°', '90°'], explanation: `Hour hand =30×2+0.5×20=70°.`, shortcut: 'The hour hand moves 0.5° each minute.', formulaIds: ['clocks'], tags: ['Clock', 'Moving hand'] });
    if (i % 5 === 3) return q('clocks', i, { prompt: 'At 4:30, the smaller angle between the hands is:', answer: '45°', wrong: ['30°', '60°', '75°'], explanation: `Hour hand=30×4+0.5×30=135°; minute hand=180°. Difference=45°.`, shortcut: 'Use |30H−5.5M|.', formulaIds: ['clocks'], tags: ['Clock', 'Angle'] });
    return q('clocks', i, { prompt: 'How many times do the hands of a clock coincide in 12 hours?', answer: '11', wrong: ['12', '10', '22'], explanation: `The minute hand catches the hour hand once every 65 5/11 minutes, giving 11 coincidences in 12 h.`, shortcut: 'It is 11, not 12—the hands do not separately coincide at both 12 endpoints.', formulaIds: ['clocks'], tags: ['Clock', 'Coincidence'] });
  },
  calendars: i => {
    if (i % 5 === 0) return q('calendars', i, { prompt: 'If 1 January is Monday in a non-leap year, 1 February is:', answer: 'Thursday', wrong: ['Tuesday', 'Wednesday', 'Friday'], explanation: `January has 31 days = 3 odd days. Monday +3 = Thursday.`, shortcut: 'Reduce month length modulo 7.', formulaIds: ['calendars'], tags: ['Calendar', 'Odd days'] });
    if (i % 5 === 1) return q('calendars', i, { prompt: 'Which is a leap year?', answer: '2024', wrong: ['1900', '2100', '2023'], explanation: `2024 is divisible by 4 and not a disallowed century. 1900 and 2100 are not divisible by 400.`, shortcut: 'Century years must be divisible by 400 to be leap years.', formulaIds: ['calendars'], tags: ['Calendar', 'Leap year'] });
    if (i % 5 === 2) return q('calendars', i, { prompt: 'If today is Wednesday, what day will it be 100 days later?', answer: 'Friday', wrong: ['Thursday', 'Saturday', 'Monday'], explanation: `100 leaves remainder 2 when divided by 7. Wednesday +2 = Friday.`, shortcut: 'Only the remainder after division by 7 matters.', formulaIds: ['calendars'], tags: ['Calendar', 'Day shift'] });
    if (i % 5 === 3) return q('calendars', i, { prompt: 'How many odd days are there in a leap year?', answer: '2', wrong: ['1', '0', '3'], explanation: `366 = 52 weeks + 2 days, so there are 2 odd days.`, shortcut: 'A normal year shifts by 1; a leap year by 2.', formulaIds: ['calendars'], tags: ['Calendar', 'Odd days'] });
    return q('calendars', i, { prompt: 'If the first day of a month is Friday, what day is the 22nd?', answer: 'Friday', wrong: ['Thursday', 'Saturday', 'Monday'], explanation: `The 22nd is 21 days after the 1st, and 21 is a multiple of 7.`, shortcut: 'Dates seven days apart share the same weekday.', formulaIds: ['calendars'], tags: ['Calendar', 'Week cycle'] });
  }
};

const diSets = [
  { title: 'Campus placements by department', labels: ['Engineering', 'Sales', 'Support', 'Finance'], values: [84, 56, 44, 36], unit: 'students' },
  { title: 'Quarterly revenue', labels: ['Q1', 'Q2', 'Q3', 'Q4'], values: [48, 60, 54, 72], unit: '₹ lakh' },
  { title: 'Weekly study hours', labels: ['Asha', 'Bala', 'Chen', 'Dev'], values: [18, 24, 20, 28], unit: 'hours' },
  { title: 'Applications cleared by round', labels: ['Screening', 'Aptitude', 'Technical', 'HR'], values: [360, 240, 144, 108], unit: 'candidates' },
  { title: 'Project time by workstream', labels: ['Research', 'Build', 'Testing', 'Review'], values: [90, 210, 120, 60], unit: 'hours' }
];
const dataInterpretation = Array.from({ length: 20 }, (_, index) => {
  const set = diSets[Math.floor(index / 4)]; const position = index % 4; const total = set.values.reduce((sum, value) => sum + value, 0); const max = Math.max(...set.values); const min = Math.min(...set.values); const first = set.values[0]; const last = set.values.at(-1); const context = { visualType: 'table', title: set.title, labels: set.labels, values: set.values, unit: set.unit };
  if (position === 0) return q('data-interpretation', index, { prompt: `What is the total shown in the table?`, answer: `${total}`, wrong: [`${total - first}`, `${total + min}`, `${max}`], explanation: `${set.values.join(' + ')} = ${total}.`, shortcut: 'Add carefully and keep the unit in view.', formulaIds: ['average'], tags: ['Data interpretation', 'Total'], setId: `foundation-di-${Math.floor(index / 4) + 1}`, setContext: context });
  if (position === 1) return q('data-interpretation', index, { prompt: `Which category has the highest value?`, answer: set.labels[set.values.indexOf(max)], wrong: set.labels.filter(label => label !== set.labels[set.values.indexOf(max)]), explanation: `${set.labels[set.values.indexOf(max)]} has ${max}, the largest entry.`, tags: ['Data interpretation', 'Comparison'], setId: `foundation-di-${Math.floor(index / 4) + 1}`, setContext: context });
  if (position === 2) return q('data-interpretation', index, { prompt: `What is the difference between the largest and smallest values?`, answer: `${max - min}`, wrong: [`${max + min}`, `${max}`, `${min}`], explanation: `${max} − ${min} = ${max - min}.`, tags: ['Data interpretation', 'Difference'], setId: `foundation-di-${Math.floor(index / 4) + 1}`, setContext: context });
  const change = (last - first) / first * 100; return q('data-interpretation', index, { prompt: `What is the percentage change from ${set.labels[0]} to ${set.labels.at(-1)}?`, answer: `${format(change)}%`, wrong: [`${last - first}%`, `${format(last / first * 100)}%`, `${format(change + 10)}%`], explanation: `(${last}−${first})/${first}×100 = ${format(change)}%.`, shortcut: 'Percentage change always uses the starting value as its base.', formulaIds: ['percentage-change'], tags: ['Data interpretation', 'Percentage change'], setId: `foundation-di-${Math.floor(index / 4) + 1}`, setContext: context });
});

const logicalBank = [
  ['Five people P, Q, R, S and T sit in a row facing north. P is immediately left of Q; S is immediately right of Q; R and T are at the ends. Who sits in the middle?', 'Q', ['P', 'R', 'S'], 'The middle block is P-Q-S, so Q is in the central seat.', 'Seating arrangement'],
  ['Pointing to a woman, Arjun says, “She is the daughter of my grandfather’s only son.” How is she related to Arjun?', 'Sister', ['Mother', 'Cousin', 'Aunt'], 'Grandfather’s only son is Arjun’s father; his daughter is Arjun’s sister.', 'Blood relation'],
  ['Meera walks 6 km north, then 4 km east, then 6 km south. Where is she from her starting point?', 'East', ['West', 'North', 'South'], 'The north and south movement cancel, leaving 4 km east.', 'Direction sense'],
  ['In a code, each letter is shifted two places forward. How is CAMP written?', 'ECOR', ['DBNQ', 'ECPR', 'DQOR'], 'C→E, A→C, M→O and P→R, so ECOR.', 'Coding-decoding'],
  ['Statements: All analysts are readers. Some readers are runners. Conclusions: I. Some analysts are runners. II. Some runners are readers. Which follows?', 'Only II follows', ['Only I follows', 'Both I and II follow', 'Neither follows'], '“Some readers are runners” guarantees II, but it does not connect analysts with runners.', 'Syllogism'],
  ['A is taller than B. B is taller than C. Which statement must be true?', 'A is taller than C', ['C is taller than A', 'A and C are equal', 'B is shortest'], 'Height order is transitive: A>B and B>C imply A>C.', 'Logical deduction'],
  ['What is x? I. x+y=12. II. y=5.', 'Both statements together are sufficient', ['I alone is sufficient', 'II alone is sufficient', 'Either alone is sufficient'], 'Statement I has two unknowns; II gives y. Together x=7.', 'Data sufficiency'],
  ['Dev is 8th from the top and 13th from the bottom in a class. How many students are there?', '20', ['21', '19', '104'], 'Total = 8+13−1 = 20 because Dev is counted twice.', 'Ranking'],
  ['Find the next term: 3, 7, 15, 31, ?', '63', ['47', '62', '64'], 'Each term is previous×2+1, so 31×2+1=63.', 'Series'],
  ['“Algorithm : Procedure” is most analogous to:', 'Blueprint : Plan', ['Compiler : Error', 'Keyboard : Screen', 'Database : Query'], 'An algorithm is a defined procedure; a blueprint is a defined plan.', 'Analogy'],
  ['Six candidates A–F are ranked. A is above B; C is above D; E is last. Which may be true?', 'A is first', ['E is first', 'B is above A', 'D is above C'], 'Only A first does not violate any stated ordering.', 'Ordering'],
  ['A clock is set correctly at noon but gains 5 minutes every hour. What time will it show at actual 6:00 pm?', '6:30 pm', ['6:05 pm', '6:25 pm', '7:00 pm'], 'It gains 5 minutes in each of 6 actual hours, for a 30-minute gain.', 'Applied reasoning'],
  ['Statement: The library has extended weekday hours during examinations. Conclusion I: Students may use it later on weekdays. II: It will remain open all night.', 'Only I follows', ['Only II follows', 'Both follow', 'Neither follows'], 'Extended hours supports I; “all night” is not stated.', 'Statement-conclusion'],
  ['Notice: “Install the update before submitting your application.” Assumptions I: The update may affect submission. II: Every applicant already has the update.', 'Only I is implicit', ['Only II is implicit', 'Both are implicit', 'Neither is implicit'], 'The instruction matters only if the update can affect submission; it does not assume all have installed it.', 'Statement-assumption'],
  ['Four interviews occur Mon–Thu. Design is before Coding; HR is Thursday; Aptitude is immediately after Design. Which is the correct order?', 'Design, Aptitude, Coding, HR', ['Aptitude, Design, Coding, HR', 'Coding, Design, Aptitude, HR', 'Design, Coding, Aptitude, HR'], 'The immediate pair Design-Aptitude must occur before Coding, and HR is Thursday.', 'Scheduling'],
  ['A, B and C have different ages. A is older than B, B older than C. If C is 18 and A is 24, which could be B’s age?', '21', ['17', '18', '25'], 'B must lie strictly between 18 and 24.', 'Ordering'],
  ['If “+” means “×”, “−” means “+”, “×” means “−”, what is 6 + 3 − 2?', '20', ['14', '16', '7'], 'Replace symbols: 6×3+2=20.', 'Symbol operation'],
  ['All roses are flowers. Some flowers fade quickly. Which conclusion is definitely true?', 'Some flowers fade quickly', ['Some roses fade quickly', 'All flowers are roses', 'No rose fades quickly'], 'This repeats the second statement; nothing links roses to the fading subset.', 'Syllogism'],
  ['A person faces east, turns right, then right again, then left. Which direction do they face now?', 'South', ['North', 'East', 'West'], 'East→South→West→South.', 'Direction sense'],
  ['In a queue, N is 12th from the front and 9th from the back. Total people are:', '20', ['21', '19', '108'], 'Total=12+9−1=20.', 'Ranking']
];
const logicalReasoning = logicalBank.map(([prompt, answer, wrong, explanation, tag], index) => q('logical-reasoning', index, { prompt, answer, wrong, explanation, shortcut: tag === 'Ranking' ? 'Add positions from both ends and subtract one.' : null, tags: ['Logical reasoning', tag] }));

const verbalBank = [
  ['Choose the grammatically correct sentence.', 'Each of the candidates has submitted a portfolio.', ['Each of the candidates have submitted a portfolio.', 'Each candidates has submitted a portfolio.', 'Each of candidate have submitted a portfolio.'], '“Each” is singular, so it takes “has”.', 'Grammar'],
  ['In “The manager gave a pragmatic response,” pragmatic most nearly means:', 'Practical', ['Emotional', 'Uncertain', 'Ornamental'], 'Pragmatic describes a practical, results-focused approach.', 'Vocabulary'],
  ['Choose the best completion: “The analyst verified the figures twice to ______ the risk of an error.”', 'Minimise', ['Magnify', 'Postpone', 'Ignore'], 'Verification reduces or minimises error risk.', 'Sentence completion'],
  ['Choose the synonym of “meticulous”.', 'Careful', ['Careless', 'Brief', 'Unclear'], 'Meticulous means very careful and precise.', 'Synonym'],
  ['Choose the most coherent order: P. It reduced deployment risk. Q. The team first added automated tests. R. They then released in smaller batches.', 'Q-R-P', ['P-Q-R', 'R-P-Q', 'Q-P-R'], 'The sequence is action (tests), then action (smaller releases), then result (reduced risk).', 'Para jumbles'],
  ['Identify the error: “Neither the mentor nor the interns was available.”', 'was available', ['Neither the mentor', 'nor the interns', 'No error'], 'With neither/nor, the verb agrees with the nearer subject; “interns were available” is needed.', 'Error detection'],
  ['A report says internship reflection improves learning when feedback is specific. Which inference is best supported?', 'Specific feedback supports the value of reflection.', ['Feedback is unnecessary.', 'All internships are identical.', 'Reflection replaces work.'], 'The statement supports targeted feedback, not any broad claim about all internships.', 'Reading comprehension'],
  ['Choose the word closest in meaning to “concise”.', 'Brief', ['Confusing', 'Lengthy', 'Hostile'], 'Concise writing uses few words without losing meaning.', 'Vocabulary'],
  ['Choose the correct sentence.', 'The data are consistent with the conclusion.', ['The data is consistent with the conclusion.', 'The datas are consistent with the conclusion.', 'The data are consist with the conclusion.'], 'In formal usage, “data” is plural and takes “are”.', 'Grammar'],
  ['The proposal was accepted ______ it addressed the budget concern.', 'because', ['although', 'unless', 'despite'], '“Because” supplies the reason for acceptance.', 'Connectors'],
  ['Which sentence is most direct and professional?', 'Please send the revised file by 4 pm.', ['It would perhaps be nice if the revised file could maybe be sent.', 'The file, which is revised, should be sent by someone.', 'Send perhaps the file which has been revised at some point.'], 'The selected sentence gives a clear action, object and deadline.', 'Professional writing'],
  ['Choose the antonym of “scarce”.', 'Abundant', ['Rare', 'Limited', 'Insufficient'], 'Scarce means in short supply; abundant is the opposite.', 'Antonym'],
  ['Select the best revision: “The team discussed about the issue.”', 'The team discussed the issue.', ['The team discussed on the issue.', 'The team had discussed about the issue.', 'The team was discussing about the issue.'], '“Discuss” takes a direct object; “about” is unnecessary.', 'Sentence correction'],
  ['Which word best completes: “Her explanation was ______ enough for everyone to follow.”', 'clear', ['obscure', 'ambiguous', 'random'], 'An explanation that people can follow is clear.', 'Sentence completion'],
  ['Choose the statement that weakens: “Shorter meetings improved output.”', 'Output was not measured before the change.', ['Saved meeting time was used for focused work.', 'The team completed more tasks after the change.', 'Members reported fewer interruptions.'], 'Without a before measurement, the causal claim is poorly supported.', 'Critical reasoning'],
  ['“Mitigate” most nearly means:', 'Reduce the severity of', ['Cause', 'Ignore', 'Celebrate'], 'To mitigate a risk is to make it less severe.', 'Vocabulary'],
  ['Choose the correct parallel construction.', 'The role requires analysing data, writing reports and presenting findings.', ['The role requires analysing data, to write reports and presenting findings.', 'The role requires to analyse data, writing reports and presentation findings.', 'The role requires analysis data, reports writing and findings presenting.'], 'All three items use the same -ing form.', 'Parallelism'],
  ['Read: “The pilot programme improved completion rates, but the sample was small.” Which conclusion is most careful?', 'The result is promising but needs a larger study.', ['The programme is proven for every group.', 'Sample size never matters.', 'Completion rates will always improve.'], 'The second clause limits certainty; more evidence is needed.', 'Reading comprehension'],
  ['Choose the correct word: “The committee reached ______ unanimous decision.”', 'a', ['an', 'the', 'no article'], '“Unanimous” begins with a consonant sound /y/, so it takes “a”.', 'Articles'],
  ['Choose the best subject line for a professional email requesting feedback.', 'Feedback requested on internship report', ['Hi', 'Important!!!', 'Report stuff'], 'A subject line should state the purpose clearly and specifically.', 'Professional writing']
];
const verbalAbility = verbalBank.map(([prompt, answer, wrong, explanation, tag], index) => q('verbal-ability', index, { prompt, answer, wrong, explanation, shortcut: tag === 'Para jumbles' ? 'Look for a natural opening, a sequence marker and then the result.' : null, tags: ['Verbal ability', tag] }));

export const aptitudeQuestions = {
  ...Object.fromEntries(Object.entries(numericBuilders).map(([id, builder]) => [id, Array.from({ length: 20 }, (_, index) => builder(index))])),
  ...Object.fromEntries(Object.entries(motionBuilders).map(([id, builder]) => [id, Array.from({ length: 20 }, (_, index) => builder(index))])),
  ...Object.fromEntries(Object.entries(algebraBuilders).map(([id, builder]) => [id, Array.from({ length: 20 }, (_, index) => builder(index))])),
  ...Object.fromEntries(Object.entries(geometryBuilders).map(([id, builder]) => [id, Array.from({ length: 20 }, (_, index) => builder(index))])),
  'data-interpretation': dataInterpretation,
  'logical-reasoning': logicalReasoning,
  'verbal-ability': verbalAbility
};

export const validateFoundationCatalog = () => {
  const formulaIds = new Set(formulaCatalog.map(item => item.id));
  const errors = [];
  for (const topic of aptitudeTopics) {
    const questions = aptitudeQuestions[topic.id] || [];
    if (questions.length !== 20) errors.push(`${topic.id}: expected 20 questions, received ${questions.length}`);
    const levelCounts = questions.reduce((all, item) => ({ ...all, [item.placementLevel]: (all[item.placementLevel] || 0) + 1 }), {});
    if (levelCounts['Conceptual Placement'] !== 5 || levelCounts['Standard Placement'] !== 10 || levelCounts['Advanced Placement'] !== 5) errors.push(`${topic.id}: expected a 5/10/5 placement-level mix`);
    questions.forEach(item => {
      if (item.options.length !== 4 || new Set(item.options).size !== 4) errors.push(`${item.id}: needs exactly four distinct options`);
      if (!Number.isInteger(item.correctAnswer) || item.correctAnswer < 0 || item.correctAnswer > 3) errors.push(`${item.id}: invalid correct-answer index`);
      if (!item.explanation || !item.tags.length || item.estimatedTimeSeconds < 30 || item.estimatedTimeSeconds > 90) errors.push(`${item.id}: needs explanation, concepts and a 30–90 second estimate`);
      item.formulaIds.forEach(id => { if (!formulaIds.has(id)) errors.push(`${item.id}: unknown formula ${id}`); });
    });
  }
  return errors;
};

const catalogErrors = validateFoundationCatalog();
if (catalogErrors.length) throw new Error(`Invalid Foundation aptitude catalog:\n${catalogErrors.join('\n')}`);
