const quiz = (id, prompt, options, correctAnswer, explanation) => ({ id, prompt, options, correctAnswer, explanation });
const topic = (id, title, overview, notes, interviewQuestions, quizQuestions) => ({ id, title, overview, notes, interviewQuestions, quiz: quizQuestions });

export const csFundamentals = [
  {
    id: 'dbms', name: 'DBMS', description: 'Build a reliable mental model for data design, transactions and querying.',
    cheatsheet: ['Primary key uniquely identifies a row', 'Normalize to reduce redundant updates', 'ACID protects transaction behavior', 'Indexes trade write cost for read speed'],
    topics: [
      topic('database-basics', 'Database basics & keys', 'A database stores related data with rules that preserve useful relationships.', ['A primary key must be unique and non-null.', 'A foreign key connects a row to a related table.', 'Choose a key based on stable identity, not display text.'], ['What is the difference between a primary key and a unique key?', 'When would you use a foreign key?'], [quiz('dbms-keys-1', 'Which constraint identifies each row uniquely and cannot be null?', ['Foreign key', 'Primary key', 'Index', 'View'], 1, 'A primary key uniquely identifies each row and cannot be null.'), quiz('dbms-keys-2', 'What does a foreign key primarily represent?', ['A sort order', 'A relationship to another table', 'A backup copy', 'A password'], 1, 'A foreign key references a key in another table to represent a relationship.')]),
      topic('normalization', 'Normalization', 'Normalization organizes attributes so updates do not create inconsistent copies of the same fact.', ['First normal form keeps values atomic.', 'Second normal form removes partial dependency on a composite key.', 'Third normal form removes non-key transitive dependency.'], ['Why can denormalization be useful?', 'Give an example of an update anomaly.'], [quiz('normalization-1', 'Which problem does normalization primarily reduce?', ['Network latency', 'Update anomalies', 'CPU scheduling', 'Password reuse'], 1, 'Normalization reduces duplicated facts that can become inconsistent during updates.'), quiz('normalization-2', 'A column depending on another non-key column is most associated with which issue?', ['Transitive dependency', 'Deadlock', 'Hash collision', 'Round robin'], 0, 'A transitive dependency occurs when a non-key attribute depends on another non-key attribute.')]),
      topic('transactions', 'Transactions & ACID', 'Transactions group changes so the database preserves correctness even when failures or concurrency occur.', ['Atomicity means all-or-nothing.', 'Consistency preserves defined rules.', 'Isolation controls visibility between transactions.', 'Durability survives a committed write.'], ['Explain ACID with a bank transfer.', 'What can a deadlock look like?'], [quiz('acid-1', 'Which ACID property means a committed change survives a crash?', ['Atomicity', 'Consistency', 'Isolation', 'Durability'], 3, 'Durability ensures committed data survives subsequent failures.'), quiz('acid-2', 'A transfer that either debits and credits or does neither demonstrates:', ['Atomicity', 'Indexing', 'Normalization', 'Replication'], 0, 'Atomicity makes a transaction all-or-nothing.')])]
  },
  {
    id: 'operating-systems', name: 'Operating Systems', description: 'Understand processes, memory and the operating-system services behind applications.',
    cheatsheet: ['A process has its own address space', 'Threads share a process address space', 'Virtual memory maps addresses to physical memory', 'Deadlock needs four conditions'],
    topics: [
      topic('processes-threads', 'Processes & threads', 'Processes isolate programs; threads are concurrent execution paths within one process.', ['Processes have separate address spaces.', 'Threads share process memory.', 'Context switches have a cost.'], ['When choose processes over threads?', 'What data do threads share?'], [quiz('os-thread-1', 'Threads in the same process normally share:', ['Program counter only', 'Address space', 'Different filesystems', 'Separate heaps'], 1, 'Threads share the address space of their process.'), quiz('os-thread-2', 'Which option provides stronger memory isolation?', ['Thread', 'Process', 'Function', 'Coroutine'], 1, 'A process has its own address space, providing stronger isolation.')]),
      topic('memory', 'Memory & virtual memory', 'Virtual memory gives each process an address space that the operating system maps to physical memory.', ['Pages are fixed-size memory blocks.', 'A page fault occurs when a needed page is not resident.', 'The stack and heap have different allocation lifecycles.'], ['What happens during a page fault?', 'Stack versus heap: when is each used?'], [quiz('os-memory-1', 'A page fault occurs when:', ['A process is compiled', 'A needed page is not in memory', 'An index is missing', 'A thread exits'], 1, 'The OS handles a page fault when the required page is not currently resident.'), quiz('os-memory-2', 'Virtual memory mainly provides:', ['A new CPU core', 'An address-space abstraction', 'A database schema', 'A network protocol'], 1, 'Virtual memory maps a process address space to physical storage.')]),
      topic('scheduling', 'CPU scheduling', 'Schedulers choose which ready work runs next, balancing response time, throughput and fairness.', ['FCFS is simple but can delay short jobs.', 'Round robin uses time slices.', 'Preemptive scheduling can interrupt a running process.'], ['Compare round robin and FCFS.', 'Why does context switching matter?'], [quiz('os-schedule-1', 'Which policy commonly rotates work using time slices?', ['Round robin', 'First normal form', 'Dijkstra', 'Two pointers'], 0, 'Round robin gives each ready task a time slice in rotation.'), quiz('os-schedule-2', 'Preemption means the OS can:', ['Interrupt running work', 'Delete memory', 'Compile SQL', 'Normalize a table'], 0, 'Preemptive scheduling can interrupt a running process to run another task.')])]
  },
  {
    id: 'computer-networks', name: 'Computer Networks', description: 'Learn how clients, servers and the internet move data reliably.',
    cheatsheet: ['DNS resolves names to addresses', 'TCP provides ordered reliable delivery', 'HTTP is an application protocol', 'TLS encrypts traffic between endpoints'],
    topics: [
      topic('network-basics', 'Network layers & addressing', 'Layered protocols make networks easier to evolve and debug.', ['IP addresses route packets between networks.', 'Ports identify services on a host.', 'A MAC address is used on the local link.'], ['What is the difference between an IP address and a port?', 'Why use layers?'], [quiz('net-basics-1', 'What does a port identify?', ['A database row', 'A service on a host', 'A CPU core', 'A git branch'], 1, 'Ports let a host direct traffic to the right service or process.'), quiz('net-basics-2', 'Which address is primarily used for routing across networks?', ['MAC address', 'IP address', 'Primary key', 'Thread ID'], 1, 'IP addresses are used by routers to forward packets across networks.')]),
      topic('http-dns', 'HTTP, DNS & TLS', 'Browsers resolve a domain, connect to a server and exchange HTTP messages—usually protected by TLS.', ['DNS maps a domain name to an address.', 'HTTP methods communicate intent.', 'TLS authenticates and encrypts HTTPS traffic.'], ['Walk through typing a URL into a browser.', 'Why is HTTPS preferred over HTTP?'], [quiz('net-http-1', 'Which system resolves a domain name to an IP address?', ['DNS', 'TLS', 'CSS', 'ORM'], 0, 'DNS resolves a domain name to an IP address.'), quiz('net-http-2', 'HTTPS adds which protection to HTTP?', ['Sorting', 'Encryption via TLS', 'A database index', 'A thread pool'], 1, 'HTTPS uses TLS to encrypt traffic and authenticate the endpoint.')]),
      topic('tcp-udp', 'TCP & UDP', 'TCP prioritizes reliable ordered delivery; UDP prioritizes low overhead and does not guarantee delivery.', ['TCP establishes a connection and acknowledges data.', 'UDP is connectionless.', 'Choose based on application requirements, not popularity.'], ['When would UDP be appropriate?', 'How does TCP recover from loss?'], [quiz('net-tcp-1', 'Which protocol guarantees ordered delivery?', ['UDP', 'TCP', 'DNS', 'ARP'], 1, 'TCP provides ordered, reliable byte-stream delivery.'), quiz('net-tcp-2', 'UDP is best described as:', ['Connectionless with low overhead', 'Always encrypted', 'A database protocol', 'A type of filesystem'], 0, 'UDP is connectionless and omits delivery and ordering guarantees.')])]
  },
  {
    id: 'oop', name: 'OOP', description: 'Practice modeling responsibilities, boundaries and reusable behavior.',
    cheatsheet: ['Encapsulation protects object invariants', 'Composition often reduces coupling', 'Inheritance expresses an is-a relationship', 'Polymorphism lets behavior vary behind one interface'],
    topics: [
      topic('oop-principles', 'Core OOP principles', 'Object-oriented design groups state and behavior around clear responsibilities.', ['Encapsulation keeps valid state behind methods.', 'Abstraction hides unnecessary detail.', 'Polymorphism allows an interface to support multiple implementations.'], ['Explain encapsulation with an example.', 'Composition versus inheritance?'], [quiz('oop-core-1', 'Keeping an object’s state private behind methods is:', ['Encapsulation', 'Pagination', 'Normalization', 'Scheduling'], 0, 'Encapsulation controls access to state and protects invariants.'), quiz('oop-core-2', 'Different implementations behind one interface demonstrate:', ['Polymorphism', 'Deadlock', 'Caching', 'Indexing'], 0, 'Polymorphism lets callers work through a common abstraction.')]),
      topic('design-principles', 'Design principles', 'Good design minimizes surprise and keeps each unit focused on one responsibility.', ['Prefer focused responsibilities.', 'Depend on abstractions when practical.', 'Avoid inheriting just to reuse implementation.'], ['What does single responsibility improve?', 'Why can tight coupling be risky?'], [quiz('oop-design-1', 'A class with one focused reason to change follows:', ['Single responsibility', 'Round robin', 'ACID', 'BFS'], 0, 'The single-responsibility principle keeps a class focused.'), quiz('oop-design-2', 'Depending directly on concrete services usually increases:', ['Coupling', 'Encryption', 'Sorting speed', 'Disk size'], 0, 'Concrete dependencies make components harder to replace or test.')])]
  },
  {
    id: 'git-github', name: 'Git & GitHub', description: 'Use version control safely for individual and team software work.',
    cheatsheet: ['Commit small coherent changes', 'Branches isolate work', 'Pull requests invite review', 'Rebase or merge consciously—do not overwrite shared history'],
    topics: [
      topic('git-basics', 'Commits, branches & remotes', 'Git records snapshots locally; remotes let teams exchange those snapshots.', ['A commit has a message and a parent history.', 'A branch is a movable reference to commits.', 'Fetch downloads remote history without changing your branch.'], ['What is the difference between fetch and pull?', 'Why use a branch?'], [quiz('git-1', 'Which command conceptually downloads remote history without merging it?', ['fetch', 'commit', 'reset', 'stash'], 0, 'Fetch updates remote-tracking information without merging it into the current branch.'), quiz('git-2', 'A branch is best described as:', ['A separate database', 'A movable pointer to commits', 'A password', 'A deployment server'], 1, 'A branch is a reference that advances as commits are added.')]),
      topic('collaboration', 'Collaboration & pull requests', 'A pull request provides a reviewable record of a proposed change before it reaches a shared branch.', ['Review scope should be understandable.', 'Resolve conflicts by understanding both changes.', 'Protect important branches from accidental force pushes.'], ['How do you approach a merge conflict?', 'What makes a pull request easy to review?'], [quiz('git-pr-1', 'A pull request is primarily used to:', ['Review a proposed change', 'Run SQL', 'Create a process', 'Encrypt TLS'], 0, 'Pull requests make proposed code changes reviewable before merging.'), quiz('git-pr-2', 'A merge conflict means:', ['Git needs help combining changes', 'The repository is deleted', 'A build is successful', 'A password expired'], 0, 'A conflict occurs when Git cannot automatically combine overlapping changes.')])]
  },
  {
    id: 'software-engineering', name: 'Software Engineering', description: 'Connect requirements, design, testing and maintenance to everyday product work.',
    cheatsheet: ['Requirements describe a problem before implementation', 'Tests verify behavior and prevent regressions', 'Observability helps explain production behavior', 'Small releases reduce risk'],
    topics: [
      topic('requirements', 'Requirements & user stories', 'Clear requirements describe the user, the outcome and the constraints before technical design begins.', ['Separate facts from assumptions.', 'Acceptance criteria make a feature testable.', 'Ask for edge cases early.'], ['What is acceptance criteria?', 'How would you clarify an ambiguous request?'], [quiz('se-req-1', 'Acceptance criteria help a team:', ['Decide whether a feature meets expectations', 'Choose a CPU', 'Resolve DNS', 'Sort arrays'], 0, 'Acceptance criteria define observable conditions for completion.'), quiz('se-req-2', 'Which is best before implementation?', ['Clarify assumptions', 'Mark it complete', 'Invent usage data', 'Skip testing'], 0, 'Clarifying assumptions reduces incorrect implementation work.')]),
      topic('testing', 'Testing & quality', 'Tests provide feedback that behavior still matches expectations as a system changes.', ['Unit tests isolate a small unit.', 'Integration tests verify components working together.', 'A bug regression test documents a repaired failure.'], ['Unit versus integration test?', 'What should a useful test assert?'], [quiz('se-test-1', 'An integration test primarily checks:', ['Multiple components working together', 'One arithmetic operation only', 'A visual logo', 'A git remote'], 0, 'Integration tests verify interaction between components or services.'), quiz('se-test-2', 'A regression test is valuable because it:', ['Guards against a repaired bug returning', 'Removes requirements', 'Creates an index', 'Replaces code review'], 0, 'A regression test preserves the expected behavior after a bug fix.')])]
  },
  {
    id: 'system-design-basics', name: 'System Design Basics', description: 'Start reasoning about scale, reliability and tradeoffs without pretending there is one universal architecture.',
    cheatsheet: ['Start with requirements and constraints', 'Cache read-heavy data deliberately', 'Use queues for decoupled asynchronous work', 'Measure before claiming a bottleneck'],
    topics: [
      topic('requirements-scale', 'Requirements & scale', 'System design begins by clarifying users, workload, data and reliability expectations.', ['Functional requirements describe capabilities.', 'Non-functional requirements describe constraints.', 'Estimates guide design tradeoffs.'], ['What questions do you ask before choosing a database?', 'How do read and write patterns affect design?'], [quiz('sd-req-1', 'What should come before choosing an architecture?', ['Clarifying requirements', 'Adding a cache', 'Choosing colors', 'Marking it solved'], 0, 'Requirements determine which architecture tradeoffs matter.'), quiz('sd-req-2', 'A non-functional requirement commonly covers:', ['Latency or reliability', 'A variable name', 'A quiz answer', 'A git commit message'], 0, 'Latency, reliability and scale are non-functional constraints.')]),
      topic('scaling-patterns', 'Scaling patterns', 'Caching, queues and horizontal scaling address different bottlenecks and must be chosen from evidence.', ['Caching can reduce repeated reads.', 'Queues decouple producers and consumers.', 'Load balancers distribute requests across instances.'], ['When would you use a queue?', 'What can go wrong with stale cache data?'], [quiz('sd-scale-1', 'A queue is useful when you want to:', ['Decouple asynchronous work', 'Store a password in plain text', 'Replace TLS', 'Sort a linked list'], 0, 'Queues let a producer hand work to consumers asynchronously.'), quiz('sd-scale-2', 'Caching most directly helps reduce:', ['Repeated expensive reads', 'All correctness concerns', 'Need for tests', 'Need for authentication'], 0, 'Caching can reduce repeated reads, but needs an invalidation strategy.')])]
  }
];

export const csSubjectById = id => csFundamentals.find(subject => subject.id === id);
export const csTopicById = (subjectId, topicId) => csSubjectById(subjectId)?.topics.find(item => item.id === topicId);
export const withoutQuizAnswers = subject => ({ ...subject, topics: subject.topics.map(item => ({ ...item, quiz: item.quiz.map(({ correctAnswer, explanation, ...question }) => question) })) });
