// Learning content only. Solved state is stored per user in ProblemProgress.
const leetCode = slug => slug ? `https://leetcode.com/problems/${slug}/` : null;
const question = (topic, id, title, difficulty, tags, slug = null) => ({
  id,
  topic,
  title,
  difficulty,
  description: `Practice the core ${topic.replace(/-/g, ' ')} technique behind ${title}. Identify edge cases before writing a solution.`,
  hint: `Start by naming the invariant or data structure that makes ${title} manageable, then test boundary cases.`,
  tags: tags.split('|'),
  externalUrl: leetCode(slug)
});
const catalog = (topic, entries) => entries.map(([id, title, difficulty, tags, slug]) => question(topic, id, title, difficulty, tags, slug));

export const dsaPracticeCatalog = {
  arrays: catalog('arrays', [
    ['array-traversal', 'Array Traversal', 'Easy', 'Array|Traversal'],
    ['maximum-element', 'Largest Element in an Array', 'Easy', 'Array|One Pass'],
    ['second-largest', 'Second Largest Element', 'Easy', 'Array|One Pass'],
    ['check-sorted', 'Check if an Array Is Sorted', 'Easy', 'Array|Traversal'],
    ['linear-search', 'Linear Search', 'Easy', 'Array|Search'],
    ['remove-duplicates', 'Remove Duplicates from Sorted Array', 'Easy', 'Array|Two Pointers', 'remove-duplicates-from-sorted-array'],
    ['rotate-array', 'Rotate Array', 'Medium', 'Array|Math', 'rotate-array'],
    ['move-zeroes', 'Move Zeroes', 'Easy', 'Array|Two Pointers', 'move-zeroes'],
    ['union-sorted-arrays', 'Union of Two Sorted Arrays', 'Medium', 'Array|Two Pointers'],
    ['missing-number', 'Missing Number', 'Easy', 'Array|Bit Manipulation', 'missing-number'],
    ['maximum-consecutive-ones', 'Maximum Consecutive Ones', 'Easy', 'Array|Sliding Window', 'max-consecutive-ones'],
    ['single-number', 'Single Number', 'Easy', 'Array|Bit Manipulation', 'single-number'],
    ['two-sum', 'Two Sum', 'Easy', 'Array|Hash Map', 'two-sum'],
    ['sort-colors', 'Sort 0s, 1s and 2s', 'Medium', 'Array|Two Pointers', 'sort-colors'],
    ['majority-element', 'Majority Element', 'Easy', 'Array|Counting', 'majority-element'],
    ['maximum-subarray', 'Maximum Subarray', 'Medium', 'Array|Dynamic Programming', 'maximum-subarray'],
    ['best-time-stock', 'Best Time to Buy and Sell Stock', 'Easy', 'Array|One Pass', 'best-time-to-buy-and-sell-stock'],
    ['rearrange-by-sign', 'Rearrange Array Elements by Sign', 'Medium', 'Array|Simulation', 'rearrange-array-elements-by-sign'],
    ['next-permutation', 'Next Permutation', 'Medium', 'Array|Two Pointers', 'next-permutation'],
    ['leaders-in-array', 'Leaders in an Array', 'Easy', 'Array|Traversal'],
    ['longest-consecutive', 'Longest Consecutive Sequence', 'Medium', 'Array|Hash Set', 'longest-consecutive-sequence'],
    ['set-matrix-zeroes', 'Set Matrix Zeroes', 'Medium', 'Array|Matrix', 'set-matrix-zeroes'],
    ['rotate-matrix', 'Rotate Image', 'Medium', 'Array|Matrix', 'rotate-image'],
    ['spiral-matrix', 'Spiral Matrix', 'Medium', 'Array|Matrix', 'spiral-matrix'],
    ['subarray-sum-k', 'Subarray Sum Equals K', 'Medium', 'Array|Prefix Sum', 'subarray-sum-equals-k'],
    ['merge-intervals', 'Merge Overlapping Intervals', 'Medium', 'Array|Intervals', 'merge-intervals'],
    ['merge-sorted-array', 'Merge Sorted Array', 'Easy', 'Array|Two Pointers', 'merge-sorted-array']
  ]),
  strings: catalog('strings', [
    ['reverse-string', 'Reverse String', 'Easy', 'String|Two Pointers', 'reverse-string'],
    ['valid-palindrome', 'Valid Palindrome', 'Easy', 'String|Two Pointers', 'valid-palindrome'],
    ['remove-outer-parentheses', 'Remove Outermost Parentheses', 'Easy', 'String|Stack', 'remove-outermost-parentheses'],
    ['largest-odd-number', 'Largest Odd Number in String', 'Easy', 'String|Greedy', 'largest-odd-number-in-string'],
    ['longest-common-prefix', 'Longest Common Prefix', 'Easy', 'String|Trie', 'longest-common-prefix'],
    ['isomorphic-strings', 'Isomorphic Strings', 'Easy', 'String|Hash Map', 'isomorphic-strings'],
    ['rotate-string', 'Rotate String', 'Easy', 'String|Simulation', 'rotate-string'],
    ['valid-anagram-string', 'Valid Anagram', 'Easy', 'String|Hash Map', 'valid-anagram'],
    ['frequency-sort', 'Sort Characters by Frequency', 'Medium', 'String|Hash Map', 'sort-characters-by-frequency'],
    ['maximum-nesting-depth', 'Maximum Nesting Depth of Parentheses', 'Easy', 'String|Stack', 'maximum-nesting-depth-of-the-parentheses'],
    ['roman-to-integer', 'Roman to Integer', 'Easy', 'String|Hash Map', 'roman-to-integer'],
    ['string-to-integer', 'String to Integer (atoi)', 'Medium', 'String|Parsing', 'string-to-integer-atoi'],
    ['count-substrings', 'Count Palindromic Substrings', 'Medium', 'String|Expand Around Center', 'palindromic-substrings'],
    ['longest-palindrome', 'Longest Palindromic Substring', 'Medium', 'String|Dynamic Programming', 'longest-palindromic-substring'],
    ['beauty-sum', 'Sum of Beauty of All Substrings', 'Medium', 'String|Frequency', 'sum-of-beauty-of-all-substrings'],
    ['reverse-words', 'Reverse Words in a String', 'Medium', 'String|Two Pointers', 'reverse-words-in-a-string'],
    ['valid-parenthesis-string', 'Valid Parenthesis String', 'Medium', 'String|Greedy', 'valid-parenthesis-string'],
    ['string-compression', 'String Compression', 'Medium', 'String|Two Pointers', 'string-compression'],
    ['longest-substring', 'Longest Substring Without Repeating Characters', 'Medium', 'String|Sliding Window', 'longest-substring-without-repeating-characters'],
    ['minimum-window', 'Minimum Window Substring', 'Hard', 'String|Sliding Window', 'minimum-window-substring']
  ]),
  hashing: catalog('hashing', [
    ['frequency-count', 'Frequency Count of Array Elements', 'Easy', 'Hash Map|Counting'],
    ['character-frequency', 'Character Frequency Counter', 'Easy', 'Hash Map|String'],
    ['highest-lowest-frequency', 'Highest and Lowest Frequency', 'Easy', 'Hash Map|Counting'],
    ['contains-duplicate', 'Contains Duplicate', 'Easy', 'Hash Set|Array', 'contains-duplicate'],
    ['two-sum-hash', 'Two Sum Using a Hash Map', 'Easy', 'Hash Map|Array', 'two-sum'],
    ['intersection-arrays', 'Intersection of Two Arrays', 'Easy', 'Hash Set|Array', 'intersection-of-two-arrays'],
    ['first-unique-character', 'First Unique Character in a String', 'Easy', 'Hash Map|String', 'first-unique-character-in-a-string'],
    ['valid-anagram-hash', 'Valid Anagram Using Hashing', 'Easy', 'Hash Map|String', 'valid-anagram'],
    ['group-anagrams', 'Group Anagrams', 'Medium', 'Hash Map|String', 'group-anagrams'],
    ['subarray-sum-hash', 'Subarray Sum Equals K', 'Medium', 'Hash Map|Prefix Sum', 'subarray-sum-equals-k'],
    ['longest-consecutive-hash', 'Longest Consecutive Sequence', 'Medium', 'Hash Set|Array', 'longest-consecutive-sequence'],
    ['top-k-frequent', 'Top K Frequent Elements', 'Medium', 'Hash Map|Heap', 'top-k-frequent-elements'],
    ['four-sum-count', '4Sum II', 'Medium', 'Hash Map|Array', '4sum-ii'],
    ['happy-number', 'Happy Number', 'Easy', 'Hash Set|Math', 'happy-number'],
    ['longest-zero-sum', 'Longest Zero Sum Subarray', 'Medium', 'Hash Map|Prefix Sum']
  ]),
  'two-pointers': catalog('two-pointers', [
    ['reverse-array', 'Reverse an Array', 'Easy', 'Two Pointers|Array'],
    ['reverse-string-pointers', 'Reverse String', 'Easy', 'Two Pointers|String', 'reverse-string'],
    ['palindrome-validation', 'Palindrome Validation', 'Easy', 'Two Pointers|String', 'valid-palindrome'],
    ['two-sum-sorted', 'Two Sum II - Sorted Input', 'Medium', 'Two Pointers|Array', 'two-sum-ii-input-array-is-sorted'],
    ['remove-duplicates-pointers', 'Remove Duplicates from Sorted Array', 'Easy', 'Two Pointers|Array', 'remove-duplicates-from-sorted-array'],
    ['move-zeroes-pointers', 'Move Zeroes', 'Easy', 'Two Pointers|Array', 'move-zeroes'],
    ['container-water', 'Container With Most Water', 'Medium', 'Two Pointers|Greedy', 'container-with-most-water'],
    ['three-sum', '3Sum', 'Medium', 'Two Pointers|Sorting', '3sum'],
    ['four-sum', '4Sum', 'Medium', 'Two Pointers|Sorting', '4sum'],
    ['trapping-rain-water', 'Trapping Rain Water', 'Hard', 'Two Pointers|Array', 'trapping-rain-water'],
    ['sorted-squares', 'Squares of a Sorted Array', 'Easy', 'Two Pointers|Array', 'squares-of-a-sorted-array'],
    ['merge-sorted-pointers', 'Merge Sorted Array', 'Easy', 'Two Pointers|Array', 'merge-sorted-array'],
    ['partition-list', 'Partition Array by Pivot', 'Medium', 'Two Pointers|Partition'],
    ['sort-colors-pointers', 'Sort Colors', 'Medium', 'Two Pointers|Array', 'sort-colors'],
    ['backspace-compare', 'Backspace String Compare', 'Easy', 'Two Pointers|String', 'backspace-string-compare']
  ]),
  'sliding-window': catalog('sliding-window', [
    ['max-sum-size-k', 'Maximum Sum Subarray of Size K', 'Easy', 'Sliding Window|Array'],
    ['first-negative-window', 'First Negative Integer in Every Window', 'Medium', 'Sliding Window|Queue'],
    ['max-ones-window', 'Max Consecutive Ones III', 'Medium', 'Sliding Window|Array', 'max-consecutive-ones-iii'],
    ['longest-substring-window', 'Longest Substring Without Repeating Characters', 'Medium', 'Sliding Window|String', 'longest-substring-without-repeating-characters'],
    ['character-replacement', 'Longest Repeating Character Replacement', 'Medium', 'Sliding Window|String', 'longest-repeating-character-replacement'],
    ['permutation-string', 'Permutation in String', 'Medium', 'Sliding Window|String', 'permutation-in-string'],
    ['fruits-baskets', 'Fruit Into Baskets', 'Medium', 'Sliding Window|Hash Map', 'fruit-into-baskets'],
    ['minimum-size-subarray', 'Minimum Size Subarray Sum', 'Medium', 'Sliding Window|Array', 'minimum-size-subarray-sum'],
    ['maximum-points-cards', 'Maximum Points You Can Obtain from Cards', 'Medium', 'Sliding Window|Array', 'maximum-points-you-can-obtain-from-cards'],
    ['binary-subarrays-sum', 'Binary Subarrays With Sum', 'Medium', 'Sliding Window|Prefix Sum', 'binary-subarrays-with-sum'],
    ['count-nice-subarrays', 'Count Number of Nice Subarrays', 'Medium', 'Sliding Window|Prefix Sum', 'count-number-of-nice-subarrays'],
    ['substrings-all-chars', 'Number of Substrings Containing All Three Characters', 'Medium', 'Sliding Window|String', 'number-of-substrings-containing-all-three-characters'],
    ['minimum-window-window', 'Minimum Window Substring', 'Hard', 'Sliding Window|String', 'minimum-window-substring'],
    ['sliding-window-maximum', 'Sliding Window Maximum', 'Hard', 'Sliding Window|Deque', 'sliding-window-maximum'],
    ['longest-limited-difference', 'Longest Continuous Subarray With Absolute Diff Limit', 'Medium', 'Sliding Window|Deque', 'longest-continuous-subarray-with-absolute-diff-less-than-or-equal-to-limit']
  ]),
  'linked-list': catalog('linked-list', [
    ['linked-list-traversal', 'Linked List Traversal', 'Easy', 'Linked List|Traversal'],
    ['linked-list-search', 'Search in Linked List', 'Easy', 'Linked List|Traversal'],
    ['insert-node', 'Insert Node in Linked List', 'Easy', 'Linked List|Implementation'],
    ['delete-node', 'Delete Node in Linked List', 'Easy', 'Linked List|Implementation'],
    ['reverse-linked-list', 'Reverse Linked List', 'Easy', 'Linked List|Pointers', 'reverse-linked-list'],
    ['middle-linked-list', 'Middle of the Linked List', 'Easy', 'Linked List|Fast Slow Pointers', 'middle-of-the-linked-list'],
    ['linked-list-cycle', 'Linked List Cycle', 'Easy', 'Linked List|Fast Slow Pointers', 'linked-list-cycle'],
    ['cycle-start', 'Linked List Cycle II', 'Medium', 'Linked List|Fast Slow Pointers', 'linked-list-cycle-ii'],
    ['palindrome-linked-list', 'Palindrome Linked List', 'Easy', 'Linked List|Two Pointers', 'palindrome-linked-list'],
    ['odd-even-list', 'Odd Even Linked List', 'Medium', 'Linked List|Pointers', 'odd-even-linked-list'],
    ['remove-nth-node', 'Remove Nth Node From End', 'Medium', 'Linked List|Two Pointers', 'remove-nth-node-from-end-of-list'],
    ['delete-middle-node', 'Delete the Middle Node', 'Medium', 'Linked List|Fast Slow Pointers', 'delete-the-middle-node-of-a-linked-list'],
    ['sort-linked-list', 'Sort List', 'Medium', 'Linked List|Merge Sort', 'sort-list'],
    ['intersection-linked-lists', 'Intersection of Two Linked Lists', 'Easy', 'Linked List|Two Pointers', 'intersection-of-two-linked-lists'],
    ['add-two-numbers', 'Add Two Numbers', 'Medium', 'Linked List|Math', 'add-two-numbers'],
    ['merge-two-lists', 'Merge Two Sorted Lists', 'Easy', 'Linked List|Recursion', 'merge-two-sorted-lists'],
    ['reverse-k-group', 'Reverse Nodes in K-Group', 'Hard', 'Linked List|Recursion', 'reverse-nodes-in-k-group'],
    ['rotate-list', 'Rotate List', 'Medium', 'Linked List|Two Pointers', 'rotate-list'],
    ['flatten-linked-list', 'Flatten a Multilevel Doubly Linked List', 'Medium', 'Linked List|Recursion', 'flatten-a-multilevel-doubly-linked-list'],
    ['copy-random-list', 'Copy List with Random Pointer', 'Medium', 'Linked List|Hash Map', 'copy-list-with-random-pointer']
  ]),
  'stack-queue': catalog('stack-queue', [
    ['implement-stack', 'Implement Stack', 'Easy', 'Stack|Implementation'],
    ['implement-queue', 'Implement Queue', 'Easy', 'Queue|Implementation'],
    ['stack-using-queues', 'Implement Stack Using Queues', 'Easy', 'Stack|Queue', 'implement-stack-using-queues'],
    ['queue-using-stacks', 'Implement Queue Using Stacks', 'Easy', 'Queue|Stack', 'implement-queue-using-stacks'],
    ['valid-parentheses', 'Valid Parentheses', 'Easy', 'Stack|String', 'valid-parentheses'],
    ['min-stack', 'Min Stack', 'Medium', 'Stack|Design', 'min-stack'],
    ['next-greater-element', 'Next Greater Element I', 'Easy', 'Stack|Monotonic Stack', 'next-greater-element-i'],
    ['next-smaller-element', 'Next Smaller Element', 'Medium', 'Stack|Monotonic Stack'],
    ['stock-span', 'Online Stock Span', 'Medium', 'Stack|Monotonic Stack', 'online-stock-span'],
    ['daily-temperatures', 'Daily Temperatures', 'Medium', 'Stack|Monotonic Stack', 'daily-temperatures'],
    ['asteroid-collision', 'Asteroid Collision', 'Medium', 'Stack|Simulation', 'asteroid-collision'],
    ['largest-histogram', 'Largest Rectangle in Histogram', 'Hard', 'Stack|Monotonic Stack', 'largest-rectangle-in-histogram'],
    ['maximal-rectangle', 'Maximal Rectangle', 'Hard', 'Stack|Matrix', 'maximal-rectangle'],
    ['window-maximum-queue', 'Sliding Window Maximum', 'Hard', 'Queue|Deque', 'sliding-window-maximum'],
    ['celebrity-problem', 'Find the Celebrity', 'Medium', 'Stack|Two Pointers', 'find-the-celebrity'],
    ['lru-cache', 'LRU Cache Concepts', 'Medium', 'Queue|Hash Map', 'lru-cache'],
    ['infix-postfix', 'Infix to Postfix Conversion', 'Medium', 'Stack|Parsing'],
    ['postfix-evaluation', 'Evaluate Reverse Polish Notation', 'Medium', 'Stack|Math', 'evaluate-reverse-polish-notation'],
    ['monotonic-stack-pattern', 'Monotonic Stack Pattern', 'Medium', 'Stack|Pattern'],
    ['remove-k-digits', 'Remove K Digits', 'Medium', 'Stack|Greedy', 'remove-k-digits']
  ]),
  'binary-search': catalog('binary-search', [
    ['binary-search', 'Binary Search', 'Easy', 'Binary Search|Array', 'binary-search'],
    ['lower-bound', 'Lower Bound', 'Easy', 'Binary Search|Array'],
    ['upper-bound', 'Upper Bound', 'Easy', 'Binary Search|Array'],
    ['search-insert', 'Search Insert Position', 'Easy', 'Binary Search|Array', 'search-insert-position'],
    ['floor-ceil', 'Floor and Ceil in Sorted Array', 'Medium', 'Binary Search|Array'],
    ['first-last-position', 'Find First and Last Position', 'Medium', 'Binary Search|Array', 'find-first-and-last-position-of-element-in-sorted-array'],
    ['count-occurrences', 'Count Occurrences in Sorted Array', 'Medium', 'Binary Search|Array'],
    ['search-rotated-array', 'Search in Rotated Sorted Array', 'Medium', 'Binary Search|Array', 'search-in-rotated-sorted-array'],
    ['minimum-rotated', 'Find Minimum in Rotated Sorted Array', 'Medium', 'Binary Search|Array', 'find-minimum-in-rotated-sorted-array'],
    ['single-sorted', 'Single Element in a Sorted Array', 'Medium', 'Binary Search|Array', 'single-element-in-a-sorted-array'],
    ['peak-element', 'Find Peak Element', 'Medium', 'Binary Search|Array', 'find-peak-element'],
    ['integer-square-root', 'Integer Square Root', 'Easy', 'Binary Search|Math', 'sqrtx'],
    ['nth-root', 'Nth Root of an Integer', 'Medium', 'Binary Search|Math'],
    ['koko-bananas', 'Koko Eating Bananas', 'Medium', 'Binary Search|Answer', 'koko-eating-bananas'],
    ['minimum-bouquets-days', 'Minimum Days to Make Bouquets', 'Medium', 'Binary Search|Answer', 'minimum-number-of-days-to-make-m-bouquets'],
    ['smallest-divisor', 'Find the Smallest Divisor', 'Medium', 'Binary Search|Answer', 'find-the-smallest-divisor-given-a-threshold'],
    ['ship-packages', 'Capacity to Ship Packages Within D Days', 'Medium', 'Binary Search|Answer', 'capacity-to-ship-packages-within-d-days'],
    ['aggressive-cows', 'Aggressive Cows', 'Hard', 'Binary Search|Answer'],
    ['allocate-books', 'Allocate Books', 'Hard', 'Binary Search|Answer'],
    ['median-two-arrays', 'Median of Two Sorted Arrays', 'Hard', 'Binary Search|Array', 'median-of-two-sorted-arrays']
  ]),
  recursion: catalog('recursion', [
    ['basic-recursion', 'Basic Recursion', 'Easy', 'Recursion|Fundamentals'],
    ['factorial', 'Factorial', 'Easy', 'Recursion|Math'],
    ['fibonacci-recursion', 'Fibonacci Number', 'Easy', 'Recursion|Math', 'fibonacci-number'],
    ['reverse-array-recursive', 'Reverse Array Recursively', 'Easy', 'Recursion|Array'],
    ['palindrome-recursive', 'Palindrome Check Recursively', 'Easy', 'Recursion|String'],
    ['generate-subsequences', 'Generate Subsequences', 'Medium', 'Recursion|Backtracking'],
    ['subset-sum', 'Subset Sum', 'Medium', 'Recursion|Backtracking'],
    ['subsets', 'Subsets', 'Medium', 'Backtracking|Array', 'subsets'],
    ['combination-sum', 'Combination Sum', 'Medium', 'Backtracking|Array', 'combination-sum'],
    ['combination-sum-ii', 'Combination Sum II', 'Medium', 'Backtracking|Array', 'combination-sum-ii'],
    ['permutations', 'Permutations', 'Medium', 'Backtracking|Array', 'permutations'],
    ['subsets-ii', 'Subsets II', 'Medium', 'Backtracking|Array', 'subsets-ii'],
    ['palindrome-partitioning', 'Palindrome Partitioning', 'Medium', 'Backtracking|String', 'palindrome-partitioning'],
    ['n-queens', 'N-Queens', 'Hard', 'Backtracking|Matrix', 'n-queens'],
    ['sudoku-solver', 'Sudoku Solver', 'Hard', 'Backtracking|Matrix', 'sudoku-solver'],
    ['word-search', 'Word Search', 'Medium', 'Backtracking|Matrix', 'word-search'],
    ['rat-maze', 'Rat in a Maze', 'Medium', 'Backtracking|Matrix'],
    ['generate-parentheses', 'Generate Parentheses', 'Medium', 'Backtracking|String', 'generate-parentheses'],
    ['letter-combinations', 'Letter Combinations of a Phone Number', 'Medium', 'Backtracking|String', 'letter-combinations-of-a-phone-number'],
    ['kth-permutation', 'Permutation Sequence', 'Hard', 'Backtracking|Math', 'permutation-sequence']
  ]),
  trees: catalog('trees', [
    ['tree-traversal', 'Binary Tree Traversal Basics', 'Easy', 'Tree|Traversal'],
    ['preorder-traversal', 'Binary Tree Preorder Traversal', 'Easy', 'Tree|DFS', 'binary-tree-preorder-traversal'],
    ['inorder-traversal', 'Binary Tree Inorder Traversal', 'Easy', 'Tree|DFS', 'binary-tree-inorder-traversal'],
    ['postorder-traversal', 'Binary Tree Postorder Traversal', 'Easy', 'Tree|DFS', 'binary-tree-postorder-traversal'],
    ['level-order', 'Binary Tree Level Order Traversal', 'Medium', 'Tree|BFS', 'binary-tree-level-order-traversal'],
    ['iterative-traversal', 'Iterative Tree Traversals', 'Medium', 'Tree|Stack'],
    ['maximum-depth-tree', 'Maximum Depth of Binary Tree', 'Easy', 'Tree|DFS', 'maximum-depth-of-binary-tree'],
    ['balanced-tree', 'Balanced Binary Tree', 'Easy', 'Tree|DFS', 'balanced-binary-tree'],
    ['diameter-tree', 'Diameter of Binary Tree', 'Easy', 'Tree|DFS', 'diameter-of-binary-tree'],
    ['maximum-path-sum', 'Binary Tree Maximum Path Sum', 'Hard', 'Tree|DFS', 'binary-tree-maximum-path-sum'],
    ['same-tree', 'Same Tree', 'Easy', 'Tree|DFS', 'same-tree'],
    ['zigzag-level-order', 'Binary Tree Zigzag Level Order Traversal', 'Medium', 'Tree|BFS', 'binary-tree-zigzag-level-order-traversal'],
    ['boundary-traversal', 'Boundary Traversal of Binary Tree', 'Medium', 'Tree|Traversal'],
    ['vertical-order', 'Vertical Order Traversal', 'Hard', 'Tree|BFS', 'vertical-order-traversal-of-a-binary-tree'],
    ['top-view', 'Top View of Binary Tree', 'Medium', 'Tree|BFS'],
    ['bottom-view', 'Bottom View of Binary Tree', 'Medium', 'Tree|BFS'],
    ['left-right-view', 'Left and Right View of Binary Tree', 'Medium', 'Tree|DFS'],
    ['symmetric-tree', 'Symmetric Tree', 'Easy', 'Tree|DFS', 'symmetric-tree'],
    ['root-node-path', 'Root to Node Path', 'Medium', 'Tree|DFS'],
    ['lowest-common-ancestor', 'Lowest Common Ancestor of a Binary Tree', 'Medium', 'Tree|DFS', 'lowest-common-ancestor-of-a-binary-tree'],
    ['maximum-width', 'Maximum Width of Binary Tree', 'Medium', 'Tree|BFS', 'maximum-width-of-binary-tree'],
    ['children-sum', 'Children Sum Property', 'Medium', 'Tree|DFS'],
    ['distance-k', 'All Nodes Distance K in Binary Tree', 'Medium', 'Tree|BFS', 'all-nodes-distance-k-in-binary-tree'],
    ['burn-tree', 'Burning Tree', 'Hard', 'Tree|BFS'],
    ['serialize-tree', 'Serialize and Deserialize Binary Tree', 'Hard', 'Tree|Design', 'serialize-and-deserialize-binary-tree']
  ]),
  bst: catalog('bst', [
    ['search-bst', 'Search in a Binary Search Tree', 'Easy', 'BST|Search', 'search-in-a-binary-search-tree'],
    ['minimum-maximum-bst', 'Minimum and Maximum in BST', 'Easy', 'BST|Traversal'],
    ['ceil-bst', 'Ceil in a Binary Search Tree', 'Medium', 'BST|Search'],
    ['floor-bst', 'Floor in a Binary Search Tree', 'Medium', 'BST|Search'],
    ['insert-bst', 'Insert into a Binary Search Tree', 'Medium', 'BST|Implementation', 'insert-into-a-binary-search-tree'],
    ['delete-bst', 'Delete Node in a BST', 'Medium', 'BST|Implementation', 'delete-node-in-a-bst'],
    ['kth-smallest-bst', 'Kth Smallest Element in a BST', 'Medium', 'BST|Inorder', 'kth-smallest-element-in-a-bst'],
    ['validate-bst', 'Validate Binary Search Tree', 'Medium', 'BST|DFS', 'validate-binary-search-tree'],
    ['lca-bst', 'Lowest Common Ancestor of a BST', 'Medium', 'BST|Search', 'lowest-common-ancestor-of-a-binary-search-tree'],
    ['bst-preorder', 'Construct BST from Preorder Traversal', 'Medium', 'BST|Recursion'],
    ['inorder-successor', 'Inorder Successor in BST', 'Medium', 'BST|Search'],
    ['inorder-predecessor', 'Inorder Predecessor in BST', 'Medium', 'BST|Search'],
    ['bst-iterator', 'Binary Search Tree Iterator', 'Medium', 'BST|Stack', 'binary-search-tree-iterator'],
    ['recover-bst', 'Recover Binary Search Tree', 'Medium', 'BST|Inorder', 'recover-binary-search-tree'],
    ['largest-bst', 'Largest BST in Binary Tree', 'Hard', 'BST|DFS']
  ]),
  heap: catalog('heap', [
    ['heap-basics', 'Heap Basics', 'Easy', 'Heap|Fundamentals'],
    ['min-heap', 'Implement Min Heap', 'Medium', 'Heap|Implementation'],
    ['max-heap', 'Implement Max Heap', 'Medium', 'Heap|Implementation'],
    ['kth-largest', 'Kth Largest Element in an Array', 'Medium', 'Heap|Array', 'kth-largest-element-in-an-array'],
    ['kth-smallest', 'Kth Smallest Element', 'Medium', 'Heap|Array'],
    ['top-k-frequent-heap', 'Top K Frequent Elements', 'Medium', 'Heap|Hash Map', 'top-k-frequent-elements'],
    ['merge-k-arrays', 'Merge K Sorted Arrays', 'Medium', 'Heap|Merge'],
    ['merge-k-lists', 'Merge k Sorted Lists', 'Hard', 'Heap|Linked List', 'merge-k-sorted-lists'],
    ['task-scheduler', 'Task Scheduler', 'Medium', 'Heap|Greedy', 'task-scheduler'],
    ['median-data-stream', 'Find Median from Data Stream', 'Hard', 'Heap|Design', 'find-median-from-data-stream'],
    ['reorganize-string', 'Reorganize String', 'Medium', 'Heap|Greedy', 'reorganize-string'],
    ['nearly-sorted-array', 'Sort a Nearly Sorted Array', 'Medium', 'Heap|Sorting'],
    ['connect-ropes', 'Connect Ropes with Minimum Cost', 'Medium', 'Heap|Greedy'],
    ['k-closest-points', 'K Closest Points to Origin', 'Medium', 'Heap|Geometry', 'k-closest-points-to-origin'],
    ['frequency-sort-heap', 'Sort Characters by Frequency', 'Medium', 'Heap|Hash Map', 'sort-characters-by-frequency']
  ]),
  greedy: catalog('greedy', [
    ['assign-cookies', 'Assign Cookies', 'Easy', 'Greedy|Sorting', 'assign-cookies'],
    ['fractional-knapsack', 'Fractional Knapsack', 'Medium', 'Greedy|Sorting'],
    ['greedy-coin-change', 'Coin Change Greedy Concepts', 'Easy', 'Greedy|Math'],
    ['lemonade-change', 'Lemonade Change', 'Easy', 'Greedy|Simulation', 'lemonade-change'],
    ['activity-selection', 'Activity Selection', 'Medium', 'Greedy|Intervals'],
    ['n-meetings', 'N Meetings in One Room', 'Medium', 'Greedy|Intervals'],
    ['jump-game', 'Jump Game', 'Medium', 'Greedy|Array', 'jump-game'],
    ['jump-game-ii', 'Jump Game II', 'Medium', 'Greedy|Array', 'jump-game-ii'],
    ['minimum-platforms', 'Minimum Platforms', 'Medium', 'Greedy|Intervals'],
    ['job-sequencing', 'Job Sequencing Problem', 'Medium', 'Greedy|Sorting'],
    ['candy', 'Candy', 'Hard', 'Greedy|Array', 'candy'],
    ['insert-interval', 'Insert Interval', 'Medium', 'Greedy|Intervals', 'insert-interval'],
    ['merge-intervals-greedy', 'Merge Intervals', 'Medium', 'Greedy|Intervals', 'merge-intervals'],
    ['non-overlapping', 'Non-overlapping Intervals', 'Medium', 'Greedy|Intervals', 'non-overlapping-intervals'],
    ['gas-station', 'Gas Station', 'Medium', 'Greedy|Array', 'gas-station']
  ]),
  graphs: catalog('graphs', [
    ['graph-representation', 'Graph Representation', 'Easy', 'Graph|Fundamentals'],
    ['graph-bfs', 'Breadth-First Search', 'Easy', 'Graph|BFS'],
    ['graph-dfs', 'Depth-First Search', 'Easy', 'Graph|DFS'],
    ['connected-components', 'Count Connected Components', 'Medium', 'Graph|DFS'],
    ['number-provinces', 'Number of Provinces', 'Medium', 'Graph|DFS', 'number-of-provinces'],
    ['number-islands', 'Number of Islands', 'Medium', 'Graph|BFS', 'number-of-islands'],
    ['flood-fill', 'Flood Fill', 'Easy', 'Graph|DFS', 'flood-fill'],
    ['rotten-oranges', 'Rotting Oranges', 'Medium', 'Graph|BFS', 'rotting-oranges'],
    ['cycle-undirected-bfs', 'Detect Cycle in Undirected Graph Using BFS', 'Medium', 'Graph|BFS'],
    ['cycle-undirected-dfs', 'Detect Cycle in Undirected Graph Using DFS', 'Medium', 'Graph|DFS'],
    ['cycle-directed', 'Detect Cycle in Directed Graph', 'Medium', 'Graph|DFS'],
    ['bipartite-graph', 'Is Graph Bipartite?', 'Medium', 'Graph|BFS', 'is-graph-bipartite'],
    ['topological-sort', 'Topological Sort', 'Medium', 'Graph|DFS'],
    ['kahns-algorithm', 'Kahn’s Algorithm', 'Medium', 'Graph|BFS'],
    ['course-schedule', 'Course Schedule', 'Medium', 'Graph|Topological Sort', 'course-schedule'],
    ['shortest-path-unweighted', 'Shortest Path in an Unweighted Graph', 'Medium', 'Graph|BFS'],
    ['dijkstra', 'Dijkstra’s Algorithm', 'Medium', 'Graph|Shortest Path'],
    ['bellman-ford', 'Bellman-Ford Algorithm', 'Medium', 'Graph|Shortest Path'],
    ['floyd-warshall', 'Floyd-Warshall Algorithm', 'Hard', 'Graph|Shortest Path'],
    ['minimum-spanning-tree', 'Minimum Spanning Tree', 'Medium', 'Graph|MST'],
    ['prims-algorithm', 'Prim’s Algorithm', 'Medium', 'Graph|MST'],
    ['kruskals-algorithm', 'Kruskal’s Algorithm', 'Medium', 'Graph|MST'],
    ['disjoint-set-union', 'Disjoint Set Union', 'Medium', 'Graph|Union Find'],
    ['word-ladder', 'Word Ladder', 'Hard', 'Graph|BFS', 'word-ladder'],
    ['cheapest-flights', 'Cheapest Flights Within K Stops', 'Medium', 'Graph|Shortest Path', 'cheapest-flights-within-k-stops']
  ]),
  'dynamic-programming': catalog('dynamic-programming', [
    ['fibonacci-dp', 'Fibonacci DP', 'Easy', 'DP|Memoization', 'fibonacci-number'],
    ['climbing-stairs', 'Climbing Stairs', 'Easy', 'DP|1D', 'climbing-stairs'],
    ['frog-jump', 'Frog Jump', 'Medium', 'DP|1D', 'frog-jump'],
    ['house-robber', 'House Robber', 'Medium', 'DP|1D', 'house-robber'],
    ['max-non-adjacent', 'Maximum Sum of Non-Adjacent Elements', 'Medium', 'DP|1D'],
    ['unique-paths', 'Unique Paths', 'Medium', 'DP|Grid', 'unique-paths'],
    ['minimum-path-sum', 'Minimum Path Sum', 'Medium', 'DP|Grid', 'minimum-path-sum'],
    ['triangle-minimum-total', 'Triangle Minimum Path Sum', 'Medium', 'DP|Grid', 'triangle'],
    ['subset-sum-dp', 'Subset Sum', 'Medium', 'DP|Knapsack'],
    ['partition-equal-subset', 'Partition Equal Subset Sum', 'Medium', 'DP|Knapsack', 'partition-equal-subset-sum'],
    ['zero-one-knapsack', '0/1 Knapsack', 'Medium', 'DP|Knapsack'],
    ['coin-change', 'Coin Change', 'Medium', 'DP|Unbounded Knapsack', 'coin-change'],
    ['target-sum', 'Target Sum', 'Medium', 'DP|Knapsack', 'target-sum'],
    ['unbounded-knapsack', 'Unbounded Knapsack', 'Medium', 'DP|Knapsack'],
    ['rod-cutting', 'Rod Cutting', 'Medium', 'DP|Knapsack'],
    ['longest-common-subsequence', 'Longest Common Subsequence', 'Medium', 'DP|String', 'longest-common-subsequence'],
    ['longest-common-substring', 'Longest Common Substring', 'Medium', 'DP|String'],
    ['edit-distance', 'Edit Distance', 'Medium', 'DP|String', 'edit-distance'],
    ['wildcard-matching', 'Wildcard Matching', 'Hard', 'DP|String', 'wildcard-matching'],
    ['longest-increasing-subsequence', 'Longest Increasing Subsequence', 'Medium', 'DP|Sequence', 'longest-increasing-subsequence'],
    ['matrix-chain', 'Matrix Chain Multiplication', 'Hard', 'DP|Partition'],
    ['palindrome-partition-dp', 'Palindrome Partitioning II', 'Hard', 'DP|Partition', 'palindrome-partitioning-ii'],
    ['stock-buy-sell-dp', 'Best Time to Buy and Sell Stock IV', 'Hard', 'DP|State Machine', 'best-time-to-buy-and-sell-stock-iv'],
    ['burst-balloons', 'Burst Balloons', 'Hard', 'DP|Interval', 'burst-balloons'],
    ['partition-array-dp', 'Partition Array for Maximum Sum', 'Hard', 'DP|Partition', 'partition-array-for-maximum-sum']
  ]),
  tries: catalog('tries', [
    ['implement-trie', 'Implement Trie', 'Medium', 'Trie|Design', 'implement-trie-prefix-tree'],
    ['trie-insert-search-prefix', 'Trie Insert, Search and Prefix', 'Medium', 'Trie|Design'],
    ['trie-count-words', 'Count Words with a Given Prefix', 'Medium', 'Trie|Counting'],
    ['trie-erase-word', 'Erase a Word from Trie', 'Medium', 'Trie|Design'],
    ['longest-word-prefixes', 'Longest Word With All Prefixes', 'Medium', 'Trie|String', 'longest-word-in-dictionary'],
    ['distinct-substrings', 'Number of Distinct Substrings', 'Hard', 'Trie|String'],
    ['maximum-xor', 'Maximum XOR of Two Numbers', 'Medium', 'Trie|Bit Manipulation', 'maximum-xor-of-two-numbers-in-an-array'],
    ['maximum-xor-queries', 'Maximum XOR With an Element From Array', 'Hard', 'Trie|Bit Manipulation', 'maximum-xor-with-an-element-from-array'],
    ['word-search-trie', 'Word Search II', 'Hard', 'Trie|Backtracking', 'word-search-ii'],
    ['autocomplete', 'Autocomplete Prefix Suggestions', 'Medium', 'Trie|Design']
  ]),
  'bit-manipulation': catalog('bit-manipulation', [
    ['check-set-clear-bit', 'Check, Set and Clear a Bit', 'Easy', 'Bit Manipulation|Fundamentals'],
    ['odd-even-bits', 'Odd or Even Using Bits', 'Easy', 'Bit Manipulation|Math'],
    ['power-of-two', 'Power of Two', 'Easy', 'Bit Manipulation|Math', 'power-of-two'],
    ['count-set-bits', 'Number of 1 Bits', 'Easy', 'Bit Manipulation|Counting', 'number-of-1-bits'],
    ['single-number-bits', 'Single Number', 'Easy', 'Bit Manipulation|XOR', 'single-number'],
    ['single-number-ii', 'Single Number II', 'Medium', 'Bit Manipulation|XOR', 'single-number-ii'],
    ['single-number-iii', 'Single Number III', 'Medium', 'Bit Manipulation|XOR', 'single-number-iii'],
    ['xor-one-to-n', 'XOR From 1 to N', 'Easy', 'Bit Manipulation|Math'],
    ['xor-range', 'XOR of Numbers in a Range', 'Medium', 'Bit Manipulation|Math'],
    ['divide-integers', 'Divide Two Integers', 'Medium', 'Bit Manipulation|Math', 'divide-two-integers'],
    ['bitmask-subsets', 'Subsets Using Bitmasks', 'Medium', 'Bit Manipulation|Backtracking'],
    ['minimum-bit-flips', 'Minimum Bit Flips to Convert Number', 'Easy', 'Bit Manipulation|XOR', 'minimum-bit-flips-to-convert-number']
  ])
};

export const questionsForTopic = topicId => dsaPracticeCatalog[topicId] || [];
export const dsaPracticeProgressId = (topicId, questionId) => `dsa:${topicId}:${questionId}`;
export const totalDsaQuestions = Object.values(dsaPracticeCatalog).reduce((total, questions) => total + questions.length, 0);
