import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../services/api.js';
import { WorkspaceLayout } from './Workspace.jsx';
import '../careerPanels.css';

const Button = ({ children, secondary = false, ...props }) => <button className={secondary ? 'button secondary' : 'button'} {...props}>{children}</button>;
const Field = ({ label, children }) => <label className="field"><span>{label}</span>{children}</label>;
const Page = ({ user, title, children, subtitle }) => <WorkspaceLayout user={user}><div className="page-header"><div><h1>{title}</h1>{subtitle && <p>{subtitle}</p>}</div></div>{children}</WorkspaceLayout>;
const emptyResume = user => ({
  name: user?.profile?.name || '', email: user?.email || '', phone: '', location: '', headline: '', summary: '',
  education: '', skills: user?.profile?.skills?.join(', ') || '', project: '', experience: ''
});
const useRecords = type => {
  const [records, setRecords] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const data = await api.records(type); setRecords(data.records); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [type]);
  return { records, setRecords, loading, error, setError, load };
};
const dateText = value => value ? new Date(value).toLocaleDateString() : '--';

export function ResumePanel({ user }) {
  const { records, loading, error, setError, load } = useRecords('resume');
  const [editing, setEditing] = useState(false); const [saving, setSaving] = useState(false); const [form, setForm] = useState(() => emptyResume(user));
  const record = records[0];
  useEffect(() => { if (!loading) { setForm(record?.data || emptyResume(user)); setEditing(!record); } }, [loading, record?.id, user]);
  const completed = ['name', 'email', 'headline', 'summary', 'education', 'skills', 'project', 'experience'].filter(key => form[key]?.trim()).length;
  const save = async event => { event.preventDefault(); setSaving(true); setError(''); try { if (record) await api.updateRecord('resume', record._id, form); else await api.createRecord('resume', form); await load(); setEditing(false); } catch (err) { setError(err.message); } finally { setSaving(false); } };
  const review = [
    form.summary?.trim() ? 'Summary added' : 'Add a short role-focused summary',
    form.project?.trim() ? 'Project evidence added' : 'Add a project with outcomes',
    /\d|%/.test(`${form.project} ${form.experience}`) ? 'Impact evidence found' : 'Add a measurable result to a project or experience',
    form.skills?.trim() ? 'Skills listed' : 'List your most relevant skills'
  ];
  return <Page user={user} title="Resume" subtitle="Build, save and print a resume from your real profile details.">
    {error && <p className="api-error">{error}</p>}
    <section className="career-split">
      <aside className="career-side"><span className="overline">COMPLETENESS</span><b>{completed} / 8 sections</b><div className="career-progress"><i style={{ width: `${completed / 8 * 100}%` }} /></div><p>Saved to your account. No sample resume is created for you.</p><Button secondary onClick={() => setEditing(value => !value)}>{editing ? 'Close editor' : record ? 'Edit resume' : 'Create resume'}</Button></aside>
      <section className="career-card resume-document">
        <div className="resume-sheet"><h2>{form.name || 'Your name'}</h2><p className="resume-contact">{[form.email, form.phone, form.location].filter(Boolean).join(' · ') || 'Add your contact details'}</p>{form.headline && <p className="resume-headline">{form.headline}</p>}<ResumeBlock title="Summary" value={form.summary} /><ResumeBlock title="Education" value={form.education} /><ResumeBlock title="Skills" value={form.skills} /><ResumeBlock title="Projects" value={form.project} /><ResumeBlock title="Experience" value={form.experience} /></div>
        <div className="career-actions"><Button secondary onClick={() => window.print()} disabled={!record}>Print / Save PDF</Button><Button secondary onClick={() => setEditing(true)}>Edit</Button></div>
      </section>
    </section>
    {editing && <form className="career-card career-form" onSubmit={save}><h2>{record ? 'Edit resume' : 'Create your resume'}</h2><div className="career-form-grid"><Field label="Full name"><input required value={form.name} onChange={event => setForm({ ...form, name: event.target.value })} /></Field><Field label="Email"><input required type="email" value={form.email} onChange={event => setForm({ ...form, email: event.target.value })} /></Field><Field label="Phone"><input value={form.phone} onChange={event => setForm({ ...form, phone: event.target.value })} placeholder="Optional" /></Field><Field label="Location"><input value={form.location} onChange={event => setForm({ ...form, location: event.target.value })} placeholder="City, State" /></Field></div><Field label="Headline"><input value={form.headline} onChange={event => setForm({ ...form, headline: event.target.value })} placeholder="e.g. Entry-level full-stack developer" /></Field><Field label="Professional summary"><textarea value={form.summary} onChange={event => setForm({ ...form, summary: event.target.value })} placeholder="Two or three concise lines about your strengths and target role." /></Field><Field label="Education"><textarea value={form.education} onChange={event => setForm({ ...form, education: event.target.value })} placeholder="Degree, college, graduation year" /></Field><Field label="Skills"><input value={form.skills} onChange={event => setForm({ ...form, skills: event.target.value })} placeholder="JavaScript, React, Node.js" /></Field><Field label="Project highlight"><textarea value={form.project} onChange={event => setForm({ ...form, project: event.target.value })} placeholder="Project, your contribution, stack and measurable result" /></Field><Field label="Experience / achievements"><textarea value={form.experience} onChange={event => setForm({ ...form, experience: event.target.value })} placeholder="Internship, leadership or achievement" /></Field><div className="career-actions"><Button secondary type="button" onClick={() => { setForm(record?.data || emptyResume(user)); setEditing(false); }}>Cancel</Button><Button disabled={saving}>{saving ? 'Saving…' : 'Save resume'}</Button></div></form>}
    <section className="career-card review-card"><div><span className="overline">RESUME REVIEW</span><h2>Useful completion checks</h2><ul>{review.map(item => <li key={item}>{item}</li>)}</ul></div><Button secondary onClick={() => setEditing(true)}>Improve resume</Button></section>
  </Page>;
}
function ResumeBlock({ title, value }) { return value?.trim() ? <section><h3>{title}</h3><p>{value}</p></section> : null; }

function RecordForm({ kind, value, onChange, onCancel, saving, onSubmit }) {
  const isJob = kind === 'job';
  return <form className="career-card career-form" onSubmit={onSubmit}><h2>{value._id ? `Edit ${isJob ? 'application' : 'project'}` : `Add ${isJob ? 'application' : 'project'}`}</h2><div className="career-form-grid">{isJob ? <><Field label="Company"><input required value={value.company || ''} onChange={event => onChange({ ...value, company: event.target.value })} /></Field><Field label="Role"><input required value={value.role || ''} onChange={event => onChange({ ...value, role: event.target.value })} /></Field><Field label="Status"><select value={value.status || 'Wishlist'} onChange={event => onChange({ ...value, status: event.target.value })}><option>Wishlist</option><option>Applied</option><option>Interviewing</option><option>Offer</option><option>Rejected</option></select></Field><Field label="Applied on"><input type="date" value={value.date || ''} onChange={event => onChange({ ...value, date: event.target.value })} /></Field></> : <><Field label="Project title"><input required value={value.title || ''} onChange={event => onChange({ ...value, title: event.target.value })} /></Field><Field label="Project link"><input type="url" value={value.link || ''} onChange={event => onChange({ ...value, link: event.target.value })} placeholder="https://… (optional)" /></Field><Field label="Tech stack"><input value={value.stack || ''} onChange={event => onChange({ ...value, stack: event.target.value })} placeholder="React, Node.js, MongoDB" /></Field><Field label="Outcome"><input value={value.outcome || ''} onChange={event => onChange({ ...value, outcome: event.target.value })} placeholder="What did this project improve or demonstrate?" /></Field></>}</div>{!isJob && <Field label="Description"><textarea value={value.description || ''} onChange={event => onChange({ ...value, description: event.target.value })} placeholder="Describe the problem, your work and a concrete result." /></Field>}<div className="career-actions"><Button secondary type="button" onClick={onCancel}>Cancel</Button><Button disabled={saving}>{saving ? 'Saving…' : 'Save'}</Button></div></form>;
}
function RecordsPanel({ user, kind }) {
  const type = kind === 'job' ? 'job' : 'project'; const label = kind === 'job' ? 'Jobs' : 'Projects'; const { records, loading, error, setError, load } = useRecords(type); const [draft, setDraft] = useState(null); const [saving, setSaving] = useState(false);
  const fresh = () => kind === 'job' ? { company: '', role: '', status: 'Wishlist', date: new Date().toISOString().slice(0, 10) } : { title: '', link: '', stack: '', outcome: '', description: '' };
  const save = async event => { event.preventDefault(); if (!draft) return; setSaving(true); setError(''); try { if (draft._id) await api.updateRecord(type, draft._id, draft); else await api.createRecord(type, draft); setDraft(null); await load(); } catch (err) { setError(err.message); } finally { setSaving(false); } };
  const remove = async record => { if (!window.confirm(`Delete this ${kind === 'job' ? 'application' : 'project'}?`)) return; try { await api.deleteRecord(type, record._id); await load(); } catch (err) { setError(err.message); } };
  return <Page user={user} title={label} subtitle={kind === 'job' ? 'Track applications and next-stage status with your own records.' : 'Capture your projects, stack, links and interview talking points.'}><div className="title-action"><h2>{kind === 'job' ? 'Applications' : 'Project portfolio'}</h2><Button onClick={() => setDraft(fresh())}>Add {kind === 'job' ? 'application' : 'project'}</Button></div>{error && <p className="api-error">{error}</p>}{draft && <RecordForm kind={kind} value={draft} onChange={setDraft} onCancel={() => setDraft(null)} saving={saving} onSubmit={save} />}{loading ? <section className="empty-panel"><p>Loading your saved records…</p></section> : records.length ? <section className="career-records">{records.map(record => <article className="career-card" key={record._id}><div>{kind === 'job' ? <><span className="overline">{record.data.status || 'Wishlist'} · {record.data.date || '--'}</span><h2>{record.data.company}</h2><p>{record.data.role}</p></> : <><span className="overline">{record.data.stack || 'Project'}</span><h2>{record.data.title}</h2><p>{record.data.description || record.data.outcome || 'No description added yet.'}</p>{record.data.outcome && <p className="record-outcome">Outcome: {record.data.outcome}</p>}{record.data.link && <a href={record.data.link} target="_blank" rel="noreferrer">Open project link ↗</a>}</>}</div><div className="career-actions"><Button secondary onClick={() => setDraft({ ...record.data, _id: record._id })}>Edit</Button><Button secondary onClick={() => void remove(record)}>Delete</Button></div></article>)}</section> : <section className="empty-panel"><h2>No {kind === 'job' ? 'applications' : 'projects'} yet</h2><p>Create a real entry to keep it here—nothing is pre-filled.</p><Button onClick={() => setDraft(fresh())}>Add your first {kind === 'job' ? 'application' : 'project'}</Button></section>}</Page>;
}
export const JobsPanel = props => <RecordsPanel {...props} kind="job" />;
export const ProjectsPanel = props => <RecordsPanel {...props} kind="project" />;

export function InterviewsPanel({ user }) {
  const types = ['Technical', 'HR', 'DSA', 'Java', 'SQL', 'Project', 'Resume'];
  const { records, loading, error, setError, load } = useRecords('interview');
  const [type, setType] = useState('Technical'); const [question, setQuestion] = useState(''); const [answer, setAnswer] = useState('');
  const [feedback, setFeedback] = useState(null); const [nextQuestion, setNextQuestion] = useState(''); const [contextual, setContextual] = useState(false); const [working, setWorking] = useState(false);
  const start = async () => { setWorking(true); setError(''); setFeedback(null); setNextQuestion(''); setAnswer(''); try { const result = await api.interview({ type }); setQuestion(result.question); setContextual(Boolean(result.contextual)); } catch (err) { setError(err.message); } finally { setWorking(false); } };
  const submit = async event => { event.preventDefault(); setWorking(true); setError(''); try { const result = await api.interview({ type, question, answer }); setQuestion(result.question); setFeedback(result.feedback); setNextQuestion(result.nextQuestion || ''); setContextual(Boolean(result.contextual)); setAnswer(''); await load(); } catch (err) { setError(err.message); } finally { setWorking(false); } };
  const continueFollowUp = () => { setQuestion(nextQuestion); setNextQuestion(''); setFeedback(null); setAnswer(''); };
  return <Page user={user} title="Interview Practice" subtitle="Choose a topic, answer out loud or in writing, then save an honest practice session.">{error && <p className="api-error">{error}</p>}<section className="career-split"><section className="career-card career-form"><span className="overline">INTERVIEW TYPE</span><h2>Choose a focus</h2><div className="choice-row">{types.map(item => <button className={type === item ? 'choice active' : 'choice'} key={item} type="button" onClick={() => { setType(item); setQuestion(''); setFeedback(null); setNextQuestion(''); }}>{item}</button>)}</div><Button onClick={() => void start()} disabled={working}>{working ? 'Loading…' : 'Start practice'}</Button></section><section className="career-card interview-question"><span className="overline">INTERVIEWER</span><h2>{question || 'Start a session to receive a question.'}</h2><p>{contextual ? 'This question uses your saved resume or project context.' : 'Answers are saved only when you submit them.'}</p></section></section>{question && <form className="career-card career-form" onSubmit={submit}><Field label="Your answer"><textarea required minLength="20" value={answer} onChange={event => setAnswer(event.target.value)} placeholder="Use context, your action, and the result. Write at least a few sentences." /></Field><div className="career-actions"><Button disabled={working}>{working ? 'Reviewing…' : 'Submit answer for feedback'}</Button></div></form>}{feedback && <section className="career-card feedback-card"><span className="overline">STRUCTURED FEEDBACK</span><h2>What to refine next</h2><ul>{feedback.map(item => <li key={item}>{item}</li>)}</ul>{nextQuestion && <div className="career-actions"><Button secondary onClick={continueFollowUp}>Continue with follow-up</Button></div>}</section>}<section className="career-card session-list"><span className="overline">SAVED PRACTICE</span><h2>Recent sessions</h2>{loading ? <p>Loading…</p> : records.length ? records.slice(0, 5).map(record => <article key={record._id}><b>{record.data.type || 'Interview'}</b><span>{dateText(record.createdAt)}</span><p>{record.data.question}</p></article>) : <p>No interview sessions yet. Start one when you are ready.</p>}</section></Page>;
}

export function CsFundamentalsPanel({ user }) {
  const [topics, setTopics] = useState([]); const [error, setError] = useState(''); const [selected, setSelected] = useState(null);
  useEffect(() => { api.csTopics().then(data => setTopics(data.topics)).catch(err => setError(err.message)); }, []);
  return <Page user={user} title="CS Fundamentals" subtitle="Select a core subject to make it the next topic you discuss, revise or ask about.">{error && <p className="api-error">{error}</p>}<section className="topic-grid">{topics.map(topic => <button className={selected === topic ? 'topic-card active' : 'topic-card'} key={topic} onClick={() => setSelected(topic)}><b>{topic}</b><span>{selected === topic ? 'Selected for revision' : 'Select topic'}</span></button>)}</section>{selected && <section className="career-card selected-topic"><div><span className="overline">NEXT REVISION TOPIC</span><h2>{selected}</h2><p>Use the coach to turn this into questions, revision notes, or an interview explanation.</p></div><Link className="button secondary" to="/help">Open AI Help</Link></section>}</Page>;
}

export function AnalyticsPanel({ user }) {
  const [data, setData] = useState(null); const [error, setError] = useState(''); useEffect(() => { api.dashboard().then(setData).catch(err => setError(err.message)); }, []); const stats = data?.stats;
  const rows = [['DSA solved', stats?.solved ?? 0], ['Foundation aptitude attempted', stats?.aptitude?.attempted ?? 0], ['Foundation accuracy', stats?.aptitude?.accuracy == null ? '--' : `${stats.aptitude.accuracy}%`], ['Advanced aptitude attempted', stats?.advancedAptitude?.attempted ?? 0], ['Interview sessions', stats?.interviews ?? 0], ['Daily tasks completed', stats?.dailyChallengesCompleted ?? 0]];
  return <Page user={user} title="Analytics" subtitle="A factual view based only on activity saved to your account.">{error && <p className="api-error">{error}</p>}<section className="metric-grid">{rows.map(([label, value]) => <article className="career-card" key={label}><span className="overline">{label}</span><b>{value}</b></article>)}</section><section className="empty-panel"><h2>{(stats?.solved || 0) + (stats?.aptitude?.attempted || 0) ? 'Keep building the signal' : 'No activity yet'}</h2><p>{(stats?.solved || 0) + (stats?.aptitude?.attempted || 0) ? 'Each submitted activity updates these figures; no demo progress is included.' : 'Solve a DSA problem or submit an aptitude set to begin tracking progress.'}</p><Link className="button" to="/dsa">Open DSA roadmap</Link></section></Page>;
}

export function WeeklyReviewPanel({ user }) {
  const { records, loading, error, setError, load } = useRecords('weekly_review'); const [form, setForm] = useState({ wins: '', gap: '', nextStep: '' }); const [saving, setSaving] = useState(false);
  const save = async event => { event.preventDefault(); setSaving(true); setError(''); try { await api.createRecord('weekly_review', { ...form, weekOf: new Date().toISOString().slice(0, 10) }); setForm({ wins: '', gap: '', nextStep: '' }); await load(); } catch (err) { setError(err.message); } finally { setSaving(false); } };
  return <Page user={user} title="Weekly Review" subtitle="Write down real wins, one gap, and the next small action.">{error && <p className="api-error">{error}</p>}<form className="career-card career-form" onSubmit={save}><Field label="What went well?"><textarea required value={form.wins} onChange={event => setForm({ ...form, wins: event.target.value })} placeholder="A real win from this week" /></Field><Field label="What needs attention?"><textarea required value={form.gap} onChange={event => setForm({ ...form, gap: event.target.value })} placeholder="One gap you want to address" /></Field><Field label="Your next concrete step"><input required value={form.nextStep} onChange={event => setForm({ ...form, nextStep: event.target.value })} placeholder="e.g. Complete one Arrays practice set on Monday" /></Field><div className="career-actions"><Button disabled={saving}>{saving ? 'Saving…' : 'Save weekly review'}</Button></div></form><section className="career-card session-list"><span className="overline">PAST REVIEWS</span><h2>Your saved reflections</h2>{loading ? <p>Loading…</p> : records.length ? records.slice(0, 6).map(record => <article key={record._id}><b>{dateText(record.data.weekOf || record.createdAt)}</b><p><strong>Win:</strong> {record.data.wins}</p><p><strong>Next:</strong> {record.data.nextStep}</p></article>) : <p>No review saved yet. Your first honest reflection will appear here.</p>}</section></Page>;
}

export function SettingsPanel({ user, onUserChange }) {
  const [form, setForm] = useState(() => ({ college: user?.profile?.college || '', degree: user?.profile?.degree || '', branch: user?.profile?.branch || '', graduationYear: user?.profile?.graduationYear || '', targetRole: user?.profile?.targetRole || '', weeklyStudyHours: user?.profile?.weeklyStudyHours || 10, skills: user?.profile?.skills?.join(', ') || '' })); const [notice, setNotice] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const save = async event => { event.preventDefault(); setSaving(true); setNotice(''); setError(''); try { const payload = { ...form, graduationYear: form.graduationYear ? Number(form.graduationYear) : undefined, weeklyStudyHours: Number(form.weeklyStudyHours), skills: form.skills.split(',').map(item => item.trim()).filter(Boolean) }; const data = await api.profile(payload); localStorage.setItem('careerforge_user', JSON.stringify(data.user)); onUserChange?.(data.user); setNotice('Settings saved.'); } catch (err) { setError(err.message); } finally { setSaving(false); } };
  return <Page user={user} title="Settings" subtitle="Manage the preparation details CareerForge stores in your profile.">{error && <p className="api-error">{error}</p>}{notice && <p className="success-note">{notice}</p>}<form className="career-card career-form" onSubmit={save}><div className="career-form-grid"><Field label="College"><input value={form.college} onChange={event => setForm({ ...form, college: event.target.value })} /></Field><Field label="Degree"><input value={form.degree} onChange={event => setForm({ ...form, degree: event.target.value })} /></Field><Field label="Branch"><input value={form.branch} onChange={event => setForm({ ...form, branch: event.target.value })} /></Field><Field label="Graduation year"><input type="number" min="2020" max="2100" value={form.graduationYear} onChange={event => setForm({ ...form, graduationYear: event.target.value })} /></Field><Field label="Target role"><input value={form.targetRole} onChange={event => setForm({ ...form, targetRole: event.target.value })} /></Field><Field label="Weekly study hours"><input required type="number" min="1" max="80" value={form.weeklyStudyHours} onChange={event => setForm({ ...form, weeklyStudyHours: event.target.value })} /></Field></div><Field label="Skills (comma-separated)"><input value={form.skills} onChange={event => setForm({ ...form, skills: event.target.value })} placeholder="Java, React, SQL" /></Field><div className="career-actions"><Button disabled={saving}>{saving ? 'Saving…' : 'Save settings'}</Button></div></form></Page>;
}
