import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { api } from '../services/api.js';
import { WorkspaceLayout } from './Workspace.jsx';
import '../phaseOne.css';

const Button = ({ children, secondary = false, ...props }) => <button className={secondary ? 'button secondary' : 'button'} {...props}>{children}</button>;
const Shell = ({ user, children }) => <WorkspaceLayout user={user}>{children}</WorkspaceLayout>;
const Page = ({ user, eyebrow, title, children, subtitle }) => <Shell user={user}><div className="page-header"><div><span className="overline">{eyebrow}</span><h1>{title}</h1>{subtitle && <p>{subtitle}</p>}</div></div>{children}</Shell>;
const ErrorState = ({ message, retry, back = '/dashboard' }) => <section className="phase-empty"><h2>We couldn’t load this page.</h2><p>{message}</p><div><Button onClick={() => void retry()}>Try again</Button><Link className="button secondary" to={back}>Go back</Link></div></section>;
const reasonOptions = ['Concept Gap', 'Calculation Error', 'Forgot Formula', 'Coding Bug', 'Misread Question', 'Time Pressure', 'Other'];

export function CsFundamentalsPanel({ user }) {
  const [data, setData] = useState(null); const [error, setError] = useState('');
  const load = async () => { try { setError(''); setData(await api.csFundamentals()); } catch (err) { setError(err.message); } };
  useEffect(() => { void load(); }, []);
  return <Page user={user} eyebrow="LEARNING · CS FUNDAMENTALS" title="CS Fundamentals" subtitle="Learn concepts, record revisions, then use a separate quiz to measure recall.">
    {error ? <ErrorState message={error} retry={load} /> : !data ? <p className="phase-loading">Loading your CS learning space…</p> : <>
      <section className="cs-intro"><div><span>LEARNING AND ASSESSMENT STAY SEPARATE</span><p>Marking a topic learned or revised records that activity. Only submitted quiz answers affect quiz accuracy.</p></div><Link className="button secondary" to="/mistakes">Open Mistake Notebook</Link></section>
      <section className="cs-subject-grid">{data.subjects.map(subject => <Link className="cs-subject-card" key={subject.id} to={`/learning/cs/${subject.id}`}><div><span>{subject.learnedCount} / {subject.topicCount} learned</span><h2>{subject.name}</h2><p>{subject.description}</p></div><footer><span>{subject.quizAttempts ? `${subject.quizAttempts} quiz attempt${subject.quizAttempts === 1 ? '' : 's'}` : 'No quiz attempts yet'}</span><b>Open →</b></footer></Link>)}</section>
    </>}
  </Page>;
}

export function CsSubjectPanel({ user }) {
  const { subjectId } = useParams(); const [data, setData] = useState(null); const [selectedId, setSelectedId] = useState(null); const [error, setError] = useState(''); const [action, setAction] = useState(''); const [quizOpen, setQuizOpen] = useState(false); const [answers, setAnswers] = useState({}); const [result, setResult] = useState(null); const [notice, setNotice] = useState('');
  const load = async () => { try { setError(''); const next = await api.csSubject(subjectId); setData(next); setSelectedId(current => current || next.subject.topics[0]?.id || null); } catch (err) { setError(err.message); } };
  useEffect(() => { void load(); }, [subjectId]);
  const subject = data?.subject; const selected = subject?.topics.find(item => item.id === selectedId);
  const updateActivity = async type => { if (!selected || action) return; setAction(type); setNotice(''); try { const response = type === 'learn' ? await api.markCsTopicLearned(subject.id, selected.id) : await api.markCsTopicRevised(subject.id, selected.id); setData(current => ({ ...current, subject: { ...current.subject, topics: current.subject.topics.map(item => item.id === selected.id ? { ...item, progress: response.progress } : item) } })); setNotice(type === 'learn' ? 'Learning progress recorded.' : 'Revision recorded. Quiz results were not changed.'); } catch (err) { setNotice(err.message); } finally { setAction(''); } };
  const submitQuiz = async event => { event.preventDefault(); if (!selected || action) return; setAction('quiz'); setNotice(''); try { const response = await api.submitCsQuiz(subject.id, selected.id, selected.quiz.map(question => ({ questionId: question.id, answer: answers[question.id] }))); setResult(response); setQuizOpen(false); setData(current => ({ ...current, subject: { ...current.subject, topics: current.subject.topics.map(item => item.id === selected.id ? { ...item, progress: response.progress } : item) } })); } catch (err) { setNotice(err.message); } finally { setAction(''); } };
  const addQuizMistake = async item => { try { await api.createMistake({ source: 'cs', questionId: `${subject.id}:${selected.id}:${item.id}`, question: item.prompt, topic: `${subject.name}: ${selected.title}`, category: subject.name, userAnswer: item.selectedAnswer === null ? 'Unanswered' : item.options[item.selectedAnswer], correctAnswer: item.options[item.correctAnswer], reason: 'Concept Gap' }); setNotice('Incorrect quiz answer saved to your Mistake Notebook.'); } catch (err) { setNotice(err.message); } };
  if (error) return <Page user={user} eyebrow="LEARNING · CS FUNDAMENTALS" title="CS Fundamentals"><ErrorState message={error} retry={load} back="/cs" /></Page>;
  if (!subject || !selected) return <Page user={user} eyebrow="LEARNING · CS FUNDAMENTALS" title="Loading subject…"><p className="phase-loading">Loading learning content…</p></Page>;
  return <Page user={user} eyebrow={`LEARNING · ${subject.name.toUpperCase()}`} title={subject.name} subtitle={subject.description}>
    <Link className="back-link" to="/cs">← All CS subjects</Link>
    <section className="cs-subject-layout"><aside className="cs-topic-list"><b>TOPICS</b>{subject.topics.map(item => <button key={item.id} className={item.id === selected.id ? 'active' : ''} onClick={() => { setSelectedId(item.id); setQuizOpen(false); setResult(null); setAnswers({}); setNotice(''); }}><span>{item.progress.learned ? '✓' : '○'}</span><div><strong>{item.title}</strong><small>{item.progress.quizAttempts ? `${item.progress.quizAccuracy ?? '--'}% quiz accuracy` : 'No quiz yet'}</small></div></button>)}</aside>
      <article className="cs-topic-detail"><div className="cs-topic-heading"><div><span className="overline">{subject.name}</span><h2>{selected.title}</h2><p>{selected.overview}</p></div><div className="cs-topic-actions"><Button secondary disabled={Boolean(action)} onClick={() => void updateActivity('learn')}>{action === 'learn' ? 'Saving…' : selected.progress.learned ? 'Learned ✓' : 'Mark learned'}</Button><Button secondary disabled={Boolean(action)} onClick={() => void updateActivity('revise')}>{action === 'revise' ? 'Saving…' : 'Mark revised'}</Button><Button disabled={Boolean(action)} onClick={() => { setQuizOpen(value => !value); setResult(null); }}>{quizOpen ? 'Close quiz' : 'Practice quiz'}</Button></div></div>
        {notice && <p className={notice.includes('recorded') || notice.includes('saved') ? 'success-note' : 'api-error'}>{notice}</p>}
        <section className="cs-content-section"><h3>Notes</h3><ul>{selected.notes.map(note => <li key={note}>{note}</li>)}</ul></section>
        <section className="cs-content-section"><h3>Interview questions</h3><ul>{selected.interviewQuestions.map(question => <li key={question}>{question}</li>)}</ul></section>
        <section className="cs-content-section"><h3>Progress</h3><p>{selected.progress.learned ? 'Learned' : 'Not marked learned'} · {selected.progress.revisionCount} revision{selected.progress.revisionCount === 1 ? '' : 's'} · {selected.progress.quizAttempts} quiz attempt{selected.progress.quizAttempts === 1 ? '' : 's'} · {selected.progress.quizAccuracy === null ? 'Quiz accuracy unavailable' : `${selected.progress.quizAccuracy}% quiz accuracy`}</p></section>
        {quizOpen && <form className="cs-quiz" onSubmit={submitQuiz}><h3>Knowledge check</h3><p>This quiz measures your answers separately from learning and revision activity.</p>{selected.quiz.map((question, questionIndex) => <fieldset key={question.id}><legend>{questionIndex + 1}. {question.prompt}</legend>{question.options.map((option, optionIndex) => <label key={option}><input type="radio" name={question.id} checked={answers[question.id] === optionIndex} onChange={() => setAnswers({ ...answers, [question.id]: optionIndex })} />{option}</label>)}</fieldset>)}<Button disabled={action === 'quiz'}>{action === 'quiz' ? 'Scoring…' : 'Submit quiz'}</Button></form>}
        {result && <section className="cs-quiz-result"><h3>Quiz result</h3><p><b>{result.attempt.correct} / {result.attempt.total}</b> correct from {result.attempt.attempted} attempted.</p>{result.review.map(item => <article className={item.selectedAnswer === item.correctAnswer ? 'correct' : 'incorrect'} key={item.id}><b>{item.prompt}</b><p>Your answer: {item.selectedAnswer === null ? 'Unanswered' : item.options[item.selectedAnswer]}</p><p>Correct answer: {item.options[item.correctAnswer]}</p><p>{item.explanation}</p>{item.selectedAnswer !== item.correctAnswer && <Button secondary onClick={() => void addQuizMistake(item)}>Add to Mistake Notebook</Button>}</article>)}</section>}
      </article></section>
    <section className="cs-cheatsheet"><span className="overline">{subject.name.toUpperCase()} CHEATSHEET</span><div>{subject.cheatsheet.map(item => <p key={item}>{item}</p>)}</div></section>
  </Page>;
}

const freshMistake = () => ({ source: 'aptitude', question: '', topic: '', category: '', userAnswer: '', correctAnswer: '', reason: 'Concept Gap', note: '' });
export function MistakeNotebookPanel({ user }) {
  const [items, setItems] = useState([]); const [source, setSource] = useState(''); const [form, setForm] = useState(freshMistake); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const data = await api.mistakes(source); setItems(data.mistakes); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [source]);
  const save = async event => { event.preventDefault(); setSaving(true); setError(''); try { await api.createMistake(form); setForm(freshMistake()); setOpen(false); await load(); } catch (err) { setError(err.message); } finally { setSaving(false); } };
  const remove = async item => { if (!window.confirm('Remove this saved mistake?')) return; try { await api.deleteMistake(item._id); await load(); } catch (err) { setError(err.message); } };
  return <Page user={user} eyebrow="WORKSPACE · REFLECTION" title="Mistake Notebook" subtitle="Save the why behind a mistake, then revisit patterns instead of repeating them.">
    <section className="mistake-toolbar"><div><span>{loading ? 'Loading…' : `${items.length} saved mistake${items.length === 1 ? '' : 's'}`}</span><select value={source} onChange={event => setSource(event.target.value)}><option value="">All sources</option><option value="dsa">DSA</option><option value="aptitude">Aptitude</option><option value="cs">CS Fundamentals</option><option value="sql">SQL</option><option value="mock">Mock test</option></select></div><Button onClick={() => setOpen(value => !value)}>{open ? 'Close form' : 'Add mistake'}</Button></section>
    {error && <section className="phase-error"><p>{error}</p><Button secondary onClick={() => void load()}>Retry</Button></section>}
    {open && <form className="mistake-form" onSubmit={save}><h2>Save a real mistake</h2><div className="mistake-form-grid"><label><span>Source</span><select value={form.source} onChange={event => setForm({ ...form, source: event.target.value })}>{['dsa', 'aptitude', 'cs', 'sql', 'mock'].map(value => <option key={value} value={value}>{value.toUpperCase()}</option>)}</select></label><label><span>Topic</span><input required value={form.topic} onChange={event => setForm({ ...form, topic: event.target.value })} placeholder="e.g. Binary Search" /></label><label><span>Category</span><input value={form.category} onChange={event => setForm({ ...form, category: event.target.value })} placeholder="Optional subtopic" /></label><label><span>Reason</span><select value={form.reason} onChange={event => setForm({ ...form, reason: event.target.value })}>{reasonOptions.map(reason => <option key={reason}>{reason}</option>)}</select></label></div><label><span>Question or situation</span><textarea required value={form.question} onChange={event => setForm({ ...form, question: event.target.value })} placeholder="What did you get wrong?" /></label><div className="mistake-form-grid"><label><span>Your answer</span><textarea value={form.userAnswer} onChange={event => setForm({ ...form, userAnswer: event.target.value })} /></label><label><span>Correct answer / approach</span><textarea value={form.correctAnswer} onChange={event => setForm({ ...form, correctAnswer: event.target.value })} /></label></div><label><span>Personal note</span><textarea value={form.note} onChange={event => setForm({ ...form, note: event.target.value })} placeholder="What will you do differently next time?" /></label><div><Button secondary type="button" onClick={() => { setForm(freshMistake()); setOpen(false); }}>Cancel</Button><Button disabled={saving}>{saving ? 'Saving…' : 'Save mistake'}</Button></div></form>}
    {!loading && !error && !items.length ? <section className="phase-empty"><h2>No mistakes saved yet.</h2><p>Mistakes you save while practising will appear here with the reason and your own note.</p><Link className="button" to="/aptitude">Start aptitude practice</Link></section> : <section className="mistake-list">{items.map(item => <article key={item._id}><header><span>{item.source.toUpperCase()} · {item.topic}</span><time>{new Date(item.occurredAt).toLocaleDateString()}</time></header><h2>{item.question}</h2>{item.category && <p className="mistake-category">{item.category}</p>}<dl><div><dt>Your answer</dt><dd>{item.userAnswer || 'Not recorded'}</dd></div><div><dt>Correct answer</dt><dd>{item.correctAnswer || 'Not recorded'}</dd></div></dl><footer><span>{item.reason}</span>{item.note && <p>{item.note}</p>}<Button secondary onClick={() => void remove(item)}>Remove</Button></footer></article>)}</section>}
  </Page>;
}
